// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as JSONSchema from "../src/JSONSchema.res.mjs";

Ava("Arrayable", (function (t) {
        t.deepEqual(JSONSchema.Arrayable.classify([
                  1,
                  2
                ]), {
              TAG: "Array",
              _0: [
                1,
                2
              ]
            }, undefined);
        t.deepEqual(JSONSchema.Arrayable.classify(1), {
              TAG: "Single",
              _0: 1
            }, undefined);
      }));

Ava("Definition", (function (t) {
        t.deepEqual({
              title: "foo"
            }, {
              title: "foo"
            }, undefined);
        t.deepEqual(true, true, undefined);
      }));

Ava("Dependency", (function (t) {
        t.deepEqual({
              title: "foo"
            }, {
              title: "foo"
            }, undefined);
        t.deepEqual([
              "field1",
              "field2"
            ], [
              "field1",
              "field2"
            ], undefined);
      }));

export {
  
}
/*  Not a pure module */
