// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as U from "./U.res.mjs";
import Ava from "ava";

var any = true;

var invalidAny = "Hello world!";

function factory() {
  return S.bool;
}

Ava("Successfully parses", (function (t) {
        var schema = S.bool;
        t.deepEqual(S.parseOrThrow(any, schema), true, undefined);
      }));

Ava("Fails to parse ", (function (t) {
        var schema = S.bool;
        U.assertThrows(t, (function () {
                return S.parseOrThrow(invalidAny, schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: schema,
                received: invalidAny
              },
              path: S.Path.empty
            });
      }));

Ava("Successfully serializes", (function (t) {
        var schema = S.bool;
        t.deepEqual(S.reverseConvertOrThrow(true, schema), any, undefined);
      }));

Ava("Compiled parse code snapshot", (function (t) {
        var schema = S.bool;
        U.assertCompiledCode(t, schema, "Parse", "i=>{if(typeof i!==\"boolean\"){e[0](i)}return i}", undefined);
      }));

Ava("Compiled serialize code snapshot", (function (t) {
        var schema = S.bool;
        U.assertCompiledCodeIsNoop(t, schema, "ReverseConvert", undefined);
      }));

Ava("Reverse schema to self", (function (t) {
        var schema = S.bool;
        t.is(S.reverse(schema), schema, undefined);
      }));

Ava("Succesfully uses reversed schema for parsing back to initial value", (function (t) {
        var schema = S.bool;
        U.assertReverseParsesBack(t, schema, true);
      }));

var Common = {
  value: true,
  any: any,
  invalidAny: invalidAny,
  factory: factory
};

Ava("Parses bool when JSON is true", (function (t) {
        t.deepEqual(S.parseOrThrow(true, S.bool), true, undefined);
      }));

Ava("Parses bool when JSON is false", (function (t) {
        t.deepEqual(S.parseOrThrow(false, S.bool), false, undefined);
      }));

export {
  Common ,
}
/*  Not a pure module */
