// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import Ava from "ava";

Ava("Initially there's no description", (function (t) {
        t.deepEqual(S.string.description, undefined, undefined);
      }));

Ava("Set description", (function (t) {
        var withDescription = S.meta(S.string, {
              description: "A useful bit of text, if you know what to do with it."
            });
        t.deepEqual(withDescription.description, "A useful bit of text, if you know what to do with it.", undefined);
        t.deepEqual(S.string.description, undefined, "Original schema is not mutated");
      }));

Ava("Transforms don't remove description", (function (t) {
        var schema = S.trim(S.meta(S.string, {
                  description: "A useful bit of text, if you know what to do with it."
                }));
        t.deepEqual(schema.description, "A useful bit of text, if you know what to do with it.", undefined);
      }));

export {
  
}
/*  Not a pure module */
