// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as U from "./U.res.mjs";
import Ava from "ava";

var any = 123;

var invalidAny = 123.45;

function factory() {
  return S.$$int;
}

Ava("Successfully parses", (function (t) {
        var schema = S.$$int;
        t.deepEqual(S.parseOrThrow(any, schema), 123, undefined);
      }));

Ava("Fails to parse", (function (t) {
        var schema = S.$$int;
        U.assertThrows(t, (function () {
                return S.parseOrThrow(invalidAny, schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: schema,
                received: invalidAny
              },
              path: S.Path.empty
            });
      }));

Ava("Successfully serializes", (function (t) {
        var schema = S.$$int;
        t.deepEqual(S.reverseConvertOrThrow(123, schema), any, undefined);
      }));

Ava("Compiled parse code snapshot", (function (t) {
        var schema = S.$$int;
        U.assertCompiledCode(t, schema, "Parse", "i=>{if(typeof i!==\"number\"||i>2147483647||i<-2147483648||i%1!==0){e[0](i)}return i}", undefined);
      }));

Ava("Compiled serialize code snapshot", (function (t) {
        var schema = S.$$int;
        U.assertCompiledCodeIsNoop(t, schema, "ReverseConvert", undefined);
      }));

Ava("Reverse schema to self", (function (t) {
        var schema = S.$$int;
        t.is(S.reverse(schema), schema, undefined);
      }));

Ava("Succesfully uses reversed schema for parsing back to initial value", (function (t) {
        var schema = S.$$int;
        U.assertReverseParsesBack(t, schema, 123);
      }));

var Common = {
  value: 123,
  any: any,
  invalidAny: invalidAny,
  factory: factory
};

Ava("Fails to parse int when JSON is a number bigger than +2^31", (function (t) {
        U.assertThrows(t, (function () {
                return S.parseOrThrow(2147483648, S.$$int);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: S.$$int,
                received: 2147483648
              },
              path: S.Path.empty
            });
        t.deepEqual(S.parseOrThrow(2147483647, S.$$int), 2147483647, undefined);
      }));

Ava("Fails to parse int when JSON is a number lower than -2^31", (function (t) {
        U.assertThrows(t, (function () {
                return S.parseOrThrow(-2147483649, S.$$int);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: S.$$int,
                received: -2147483649
              },
              path: S.Path.empty
            });
        t.deepEqual(S.parseOrThrow(-2147483648, S.$$int), -2147483648, undefined);
      }));

Ava("Fails to parse NaN", (function (t) {
        U.assertThrows(t, (function () {
                return S.parseOrThrow(NaN, S.$$int);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: S.$$int,
                received: NaN
              },
              path: S.Path.empty
            });
      }));

export {
  Common ,
}
/*  Not a pure module */
