// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as U from "./U.res.mjs";
import Ava from "ava";

var invalidValue = true;

var any = false;

var invalidAny = true;

var invalidTypeAny = "Hello world!";

function factory() {
  return S.literal(false);
}

Ava("Successfully parses", (function (t) {
        var schema = S.literal(false);
        t.deepEqual(S.parseOrThrow(any, schema), false, undefined);
      }));

Ava("Fails to parse invalid value", (function (t) {
        var schema = S.literal(false);
        U.assertThrows(t, (function () {
                return S.parseOrThrow(invalidAny, schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: S.literal(false),
                received: true
              },
              path: S.Path.empty
            });
      }));

Ava("Fails to parse invalid type", (function (t) {
        var schema = S.literal(false);
        U.assertThrows(t, (function () {
                return S.parseOrThrow(invalidTypeAny, schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: S.literal(false),
                received: invalidTypeAny
              },
              path: S.Path.empty
            });
      }));

Ava("Successfully serializes", (function (t) {
        var schema = S.literal(false);
        t.deepEqual(S.reverseConvertOrThrow(false, schema), any, undefined);
      }));

Ava("Fails to serialize invalid value", (function (t) {
        var schema = S.literal(false);
        U.assertThrows(t, (function () {
                return S.reverseConvertOrThrow(invalidValue, schema);
              }), {
              operation: "ReverseConvert",
              code: {
                TAG: "InvalidType",
                expected: S.literal(false),
                received: invalidValue
              },
              path: S.Path.empty
            });
      }));

Ava("Compiled parse code snapshot", (function (t) {
        var schema = S.literal(false);
        U.assertCompiledCode(t, schema, "Parse", "i=>{if(i!==false){e[0](i)}return i}", undefined);
      }));

Ava("Compiled serialize code snapshot", (function (t) {
        var schema = S.literal(false);
        U.assertCompiledCode(t, schema, "ReverseConvert", "i=>{if(i!==false){e[0](i)}return i}", undefined);
      }));

Ava("Reverse schema to self", (function (t) {
        var schema = S.literal(false);
        t.is(S.reverse(schema), schema, undefined);
      }));

Ava("Succesfully uses reversed schema for parsing back to initial value", (function (t) {
        var schema = S.literal(false);
        U.assertReverseParsesBack(t, schema, false);
      }));

var Common = {
  value: false,
  invalidValue: invalidValue,
  any: any,
  invalidAny: invalidAny,
  invalidTypeAny: invalidTypeAny,
  factory: factory
};

export {
  Common ,
}
/*  Not a pure module */
