// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as U from "./U.res.mjs";
import Ava from "ava";

var invalidValue = 123;

var any = undefined;

var invalidTypeAny = "Hello world!";

function factory() {
  return S.literal();
}

Ava("Successfully parses", (function (t) {
        var schema = S.literal();
        t.deepEqual(S.parseOrThrow(any, schema), undefined, undefined);
      }));

Ava("Fails to parse invalid type", (function (t) {
        var schema = S.literal();
        U.assertThrows(t, (function () {
                S.parseOrThrow(invalidTypeAny, schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: S.literal(undefined),
                received: invalidTypeAny
              },
              path: S.Path.empty
            });
      }));

Ava("Successfully serializes", (function (t) {
        var schema = S.literal();
        t.deepEqual(S.reverseConvertOrThrow(undefined, schema), any, undefined);
      }));

Ava("Fails to serialize invalid value", (function (t) {
        var schema = S.literal();
        U.assertThrows(t, (function () {
                return S.reverseConvertOrThrow(invalidValue, schema);
              }), {
              operation: "ReverseConvert",
              code: {
                TAG: "InvalidType",
                expected: S.literal(undefined),
                received: invalidValue
              },
              path: S.Path.empty
            });
      }));

Ava("Compiled parse code snapshot", (function (t) {
        var schema = S.literal();
        U.assertCompiledCode(t, schema, "Parse", "i=>{if(i!==void 0){e[0](i)}return i}", undefined);
      }));

Ava("Compiled serialize code snapshot", (function (t) {
        var schema = S.literal();
        U.assertCompiledCode(t, schema, "ReverseConvert", "i=>{if(i!==void 0){e[0](i)}return i}", undefined);
      }));

Ava("Reverse schema to self", (function (t) {
        var schema = S.literal();
        t.is(S.reverse(schema), schema, undefined);
      }));

Ava("Succesfully uses reversed schema for parsing back to initial value", (function (t) {
        var schema = S.literal();
        U.assertReverseParsesBack(t, schema, undefined);
      }));

var Common = {
  value: undefined,
  invalidValue: invalidValue,
  any: any,
  invalidTypeAny: invalidTypeAny,
  factory: factory
};

export {
  Common ,
}
/*  Not a pure module */
