// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import Ava from "ava";

Ava("Gets default value when Option.getOr is used", (function (t) {
        var schema = S.$$Option.getOr(S.option(S.$$float), 123);
        t.deepEqual(S.$$Option.$$default(schema), {
              TAG: "Value",
              _0: 123
            }, undefined);
      }));

Ava("Returns the last default value", (function (t) {
        var schema = S.$$Option.getOr(S.transform(S.$$Option.getOr(S.option(S.$$float), 123), (function (param) {
                    return {
                            p: (function (number) {
                                if (number > 0) {
                                  return "positive";
                                }
                                
                              })
                          };
                  })), "not positive");
        t.deepEqual(S.$$Option.$$default(schema), {
              TAG: "Value",
              _0: "not positive"
            }, undefined);
      }));

Ava("Gets default value when Option.getOrWith is used", (function (t) {
        var cb = function () {
          return 123;
        };
        var schema = S.$$Option.getOrWith(S.option(S.$$float), cb);
        t.deepEqual(S.$$Option.$$default(schema), {
              TAG: "Callback",
              _0: cb
            }, undefined);
      }));

Ava("Doesn't get default value for schemas without default", (function (t) {
        t.deepEqual(S.$$Option.$$default(S.$$float), undefined, undefined);
      }));

export {
  
}
/*  Not a pure module */
