// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import Ava from "ava";

Ava("Works with empty", (function (t) {
        t.deepEqual(S.Path.fromArray([]), S.Path.empty, undefined);
      }));

Ava("Works with single location", (function (t) {
        t.deepEqual(S.Path.fromArray(["123"]), S.Path.fromLocation("123"), undefined);
      }));

Ava("Works with nested location", (function (t) {
        t.deepEqual(S.Path.fromArray([
                  "1",
                  "2"
                ]), S.Path.concat(S.Path.fromLocation("1"), S.Path.fromLocation("2")), undefined);
      }));

Ava("Works with path like location", (function (t) {
        var pathLikeLocation = S.Path.fromArray([
              "1",
              "2"
            ]);
        t.deepEqual(S.Path.fromArray([pathLikeLocation]), S.Path.fromLocation(pathLikeLocation), undefined);
      }));

export {
  
}
/*  Not a pure module */
