// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as U from "./U.res.mjs";
import Ava from "ava";

Ava("Successfully parses valid data", (function (t) {
        var schema = S.uuid(S.string, undefined);
        t.deepEqual(S.parseOrThrow("123e4567-e89b-12d3-a456-426614174000", schema), "123e4567-e89b-12d3-a456-426614174000", undefined);
      }));

Ava("Successfully parses uuid V7", (function (t) {
        var schema = S.uuid(S.string, undefined);
        t.deepEqual(S.parseOrThrow("019122ba-bb79-75ef-9a97-190f1effbb54", schema), "019122ba-bb79-75ef-9a97-190f1effbb54", undefined);
      }));

Ava("Fails to parse invalid data", (function (t) {
        var schema = S.uuid(S.string, undefined);
        U.assertThrows(t, (function () {
                return S.parseOrThrow("123e4567", schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "OperationFailed",
                _0: "Invalid UUID"
              },
              path: S.Path.empty
            });
      }));

Ava("Successfully serializes valid value", (function (t) {
        var schema = S.uuid(S.string, undefined);
        t.deepEqual(S.reverseConvertOrThrow("123e4567-e89b-12d3-a456-426614174000", schema), "123e4567-e89b-12d3-a456-426614174000", undefined);
      }));

Ava("Fails to serialize invalid value", (function (t) {
        var schema = S.uuid(S.string, undefined);
        U.assertThrows(t, (function () {
                return S.reverseConvertOrThrow("123e4567", schema);
              }), {
              operation: "ReverseConvert",
              code: {
                TAG: "OperationFailed",
                _0: "Invalid UUID"
              },
              path: S.Path.empty
            });
      }));

Ava("Returns custom error message", (function (t) {
        var schema = S.uuid(S.string, "Custom");
        U.assertThrows(t, (function () {
                return S.parseOrThrow("abc", schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "OperationFailed",
                _0: "Custom"
              },
              path: S.Path.empty
            });
      }));

export {
  
}
/*  Not a pure module */
