// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as U from "./U.res.mjs";
import Ava from "ava";

Ava("Successfully parses valid data", (function (t) {
        var schema = S.url(S.string, undefined);
        t.deepEqual(S.parseOrThrow("http://dzakh.dev", schema), "http://dzakh.dev", undefined);
      }));

Ava("Fails to parse invalid data", (function (t) {
        var schema = S.url(S.string, undefined);
        U.assertThrows(t, (function () {
                return S.parseOrThrow("cifjhdsfhsd", schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "OperationFailed",
                _0: "Invalid url"
              },
              path: S.Path.empty
            });
      }));

Ava("Successfully serializes valid value", (function (t) {
        var schema = S.url(S.string, undefined);
        t.deepEqual(S.reverseConvertOrThrow("http://dzakh.dev", schema), "http://dzakh.dev", undefined);
      }));

Ava("Fails to serialize invalid value", (function (t) {
        var schema = S.url(S.string, undefined);
        U.assertThrows(t, (function () {
                return S.reverseConvertOrThrow("cifjhdsfhsd", schema);
              }), {
              operation: "ReverseConvert",
              code: {
                TAG: "OperationFailed",
                _0: "Invalid url"
              },
              path: S.Path.empty
            });
      }));

Ava("Returns custom error message", (function (t) {
        var schema = S.url(S.string, "Custom");
        U.assertThrows(t, (function () {
                return S.parseOrThrow("abc", schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "OperationFailed",
                _0: "Custom"
              },
              path: S.Path.empty
            });
      }));

export {
  
}
/*  Not a pure module */
