// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as U from "./U.res.mjs";
import Ava from "ava";

Ava("Successfully parses valid data", (function (t) {
        var schema = S.email(S.string, undefined);
        t.deepEqual(S.parseOrThrow("dzakh.dev@gmail.com", schema), "dzakh.dev@gmail.com", undefined);
      }));

Ava("Fails to parse invalid data", (function (t) {
        var schema = S.email(S.string, undefined);
        U.assertThrows(t, (function () {
                return S.parseOrThrow("dzakh.dev", schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "OperationFailed",
                _0: "Invalid email address"
              },
              path: S.Path.empty
            });
      }));

Ava("Successfully serializes valid value", (function (t) {
        var schema = S.email(S.string, undefined);
        t.deepEqual(S.reverseConvertOrThrow("dzakh.dev@gmail.com", schema), "dzakh.dev@gmail.com", undefined);
      }));

Ava("Fails to serialize invalid value", (function (t) {
        var schema = S.email(S.string, undefined);
        U.assertThrows(t, (function () {
                return S.reverseConvertOrThrow("dzakh.dev", schema);
              }), {
              operation: "ReverseConvert",
              code: {
                TAG: "OperationFailed",
                _0: "Invalid email address"
              },
              path: S.Path.empty
            });
      }));

Ava("Returns custom error message", (function (t) {
        var schema = S.email(S.string, "Custom");
        U.assertThrows(t, (function () {
                return S.parseOrThrow("dzakh.dev", schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "OperationFailed",
                _0: "Custom"
              },
              path: S.Path.empty
            });
      }));

Ava("Returns refinement", (function (t) {
        var schema = S.email(S.string, undefined);
        t.deepEqual(S.$$String.refinements(schema), [{
                kind: "Email",
                message: "Invalid email address"
              }], undefined);
      }));

export {
  
}
/*  Not a pure module */
