// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as U from "./U.res.mjs";
import Ava from "ava";

var any = [123];

var invalidAny = [123, true];

var invalidTypeAny = "Hello world!";

function factory() {
  return S.tuple1(S.$$int);
}

Ava("Successfully parses", (function (t) {
        var schema = S.tuple1(S.$$int);
        t.deepEqual(S.parseOrThrow(any, schema), 123, undefined);
      }));

Ava("Fails to parse extra item in strict mode", (function (t) {
        var schema = S.strict(S.tuple1(S.$$int));
        U.assertThrows(t, (function () {
                return S.parseOrThrow(invalidAny, schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: schema,
                received: invalidAny
              },
              path: S.Path.empty
            });
      }));

Ava("Fails to parse invalid type", (function (t) {
        var schema = S.tuple1(S.$$int);
        U.assertThrows(t, (function () {
                return S.parseOrThrow(invalidTypeAny, schema);
              }), {
              operation: "Parse",
              code: {
                TAG: "InvalidType",
                expected: schema,
                received: invalidTypeAny
              },
              path: S.Path.empty
            });
      }));

Ava("Successfully serializes", (function (t) {
        var schema = S.tuple1(S.$$int);
        t.deepEqual(S.reverseConvertOrThrow(123, schema), any, undefined);
      }));

var Common = {
  value: 123,
  any: any,
  invalidAny: invalidAny,
  invalidTypeAny: invalidTypeAny,
  factory: factory
};

export {
  Common ,
}
/*  Not a pure module */
