// @generated by protoc-gen-sury with parameter "target=ts,import_extension=js"
// @generated from file google/protobuf/empty.proto (package google.protobuf, syntax proto3)
/* eslint-disable */

import * as S from "sury";

/**
 * A generic empty message that you can re-use to avoid defining duplicated
 * empty messages in your APIs. A typical example is to use it as the request
 * or the response type of an API method. For instance:
 *
 *     service Foo {
 *       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
 *     }
 *
 *
 * @generated from message google.protobuf.Empty
 */
export type Empty = {};

export const EmptySchema = S.meta(/* @__PURE__ */ S.schemaOf<Empty>()({}), { name: "Empty" });
