// @generated by protoc-gen-sury with parameter "target=ts,import_extension=js"
// @generated from file google/protobuf/wrappers.proto (package google.protobuf, syntax proto3)
/* eslint-disable */

import * as S from "sury";

const $number = S.union([S.number, S.schema(NaN)]);

/**
 * Wrapper message for `double`.
 *
 * The JSON representation for `DoubleValue` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.DoubleValue
 */
export type DoubleValue = {
  /**
   * The double value.
   *
   * @generated from field: double value = 1;
   */
  value: number;
};

export const DoubleValueSchema = S.meta(S.schemaOf<DoubleValue>()({
  value: S.protobufField($number, { number: 1, type: "double" }),
}), { name: "DoubleValue" });

/**
 * Wrapper message for `float`.
 *
 * The JSON representation for `FloatValue` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.FloatValue
 */
export type FloatValue = {
  /**
   * The float value.
   *
   * @generated from field: float value = 1;
   */
  value: number;
};

export const FloatValueSchema = S.meta(S.schemaOf<FloatValue>()({
  value: S.protobufField($number, { number: 1, type: "float" }),
}), { name: "FloatValue" });

/**
 * Wrapper message for `int64`.
 *
 * The JSON representation for `Int64Value` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.Int64Value
 */
export type Int64Value = {
  /**
   * The int64 value.
   *
   * @generated from field: int64 value = 1;
   */
  value: bigint;
};

export const Int64ValueSchema = S.meta(S.schemaOf<Int64Value>()({
  value: S.protobufField(S.bigint, { number: 1, type: "int64" }),
}), { name: "Int64Value" });

/**
 * Wrapper message for `uint64`.
 *
 * The JSON representation for `UInt64Value` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.UInt64Value
 */
export type UInt64Value = {
  /**
   * The uint64 value.
   *
   * @generated from field: uint64 value = 1;
   */
  value: bigint;
};

export const UInt64ValueSchema = S.meta(S.schemaOf<UInt64Value>()({
  value: S.protobufField(S.bigint, { number: 1, type: "uint64" }),
}), { name: "UInt64Value" });

/**
 * Wrapper message for `int32`.
 *
 * The JSON representation for `Int32Value` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.Int32Value
 */
export type Int32Value = {
  /**
   * The int32 value.
   *
   * @generated from field: int32 value = 1;
   */
  value: number;
};

export const Int32ValueSchema = S.meta(S.schemaOf<Int32Value>()({
  value: S.protobufField(S.int32, { number: 1, type: "int32" }),
}), { name: "Int32Value" });

/**
 * Wrapper message for `uint32`.
 *
 * The JSON representation for `UInt32Value` is JSON number.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.UInt32Value
 */
export type UInt32Value = {
  /**
   * The uint32 value.
   *
   * @generated from field: uint32 value = 1;
   */
  value: number;
};

export const UInt32ValueSchema = S.meta(S.schemaOf<UInt32Value>()({
  value: S.protobufField(S.integer, { number: 1, type: "uint32" }),
}), { name: "UInt32Value" });

/**
 * Wrapper message for `bool`.
 *
 * The JSON representation for `BoolValue` is JSON `true` and `false`.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.BoolValue
 */
export type BoolValue = {
  /**
   * The bool value.
   *
   * @generated from field: bool value = 1;
   */
  value: boolean;
};

export const BoolValueSchema = S.meta(S.schemaOf<BoolValue>()({
  value: S.protobufField(S.boolean, { number: 1, type: "bool" }),
}), { name: "BoolValue" });

/**
 * Wrapper message for `string`.
 *
 * The JSON representation for `StringValue` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.StringValue
 */
export type StringValue = {
  /**
   * The string value.
   *
   * @generated from field: string value = 1;
   */
  value: string;
};

export const StringValueSchema = S.meta(S.schemaOf<StringValue>()({
  value: S.protobufField(S.string, { number: 1, type: "string" }),
}), { name: "StringValue" });

/**
 * Wrapper message for `bytes`.
 *
 * The JSON representation for `BytesValue` is JSON string.
 *
 * Not recommended for use in new APIs, but still useful for legacy APIs and
 * has no plan to be removed.
 *
 * @generated from message google.protobuf.BytesValue
 */
export type BytesValue = {
  /**
   * The bytes value.
   *
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;
};

export const BytesValueSchema = S.meta(S.schemaOf<BytesValue>()({
  value: S.protobufField(S.uint8Array, { number: 1, type: "bytes" }),
}), { name: "BytesValue" });
