// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import Ava from "ava";

let simpleObjectSchema = S.schema(s => ({
  label: s.m(S.string),
  value: s.m(S.int)
}));

Ava("Simple object schema", t => {
  U.assertEqualSchemas(t, simpleObjectSchema, S.object(s => ({
    label: s.f("label", S.string),
    value: s.f("value", S.int)
  })), undefined);
  t.deepEqual(S.parseOrThrow({label:"foo",value:1}, simpleObjectSchema), {
    label: "foo",
    value: 1
  }, undefined);
});

export {
  simpleObjectSchema,
}
/* simpleObjectSchema Not a pure module */
