/* @ts-self-types="./S.d.ts" */
import * as S from "./Sury.res.mjs"
var _void = /*#__PURE__*/ S.unit()
export { _void as void }
export var Error = S.$$Error.$$class
export var string = /*#__PURE__*/ S.string()
export var boolean = /*#__PURE__*/ S.bool()
export var int32 = /*#__PURE__*/ S.int()
export var number = /*#__PURE__*/ S.float()
export var bigint = /*#__PURE__*/ S.bigint()
export var symbol = /*#__PURE__*/ S.symbol()
export var never = /*#__PURE__*/ S.never_()
export var unknown = S.unknown
export var any = S.unknown
export var optional = S.js_optional
export var nullable = S.js_nullable
export var nullish = S.nullable
export var array = S.array
export var compactColumns = S.compactColumns
export var instance = S.instance
export var unnest = S.unnest
export var record = S.dict
export var json = /*#__PURE__*/ S.json()
export var jsonString = /*#__PURE__*/ S.jsonString()
export var jsonStringWithSpace = S.jsonStringWithSpace
export var uint8Array = /*#__PURE__*/ S.uint8Array()
export var date = /*#__PURE__*/ S.date()
export var isoDateTime = /*#__PURE__*/ S.isoDateTime()
export var union = S.js_union
export var object = S.object
export var schema = S.js_schema
export var safe = S.js_safe
export var safeAsync = S.js_safeAsync
export var reverse = S.reverse
export var parser = S.js_parser
export var asyncParser = S.js_asyncParser
export var decoder = S.getDecoder
export var asyncDecoder = S.js_asyncDecoder
export var encoder = S.js_encoder
export var asyncEncoder = S.js_asyncEncoder
export var assert = S.js_assert
export var recursive = S.recursive
export var merge = S.js_merge
export var strict = S.strict
export var deepStrict = S.deepStrict
export var strip = S.strip
export var deepStrip = S.deepStrip
export var to = S.js_to
export var toJSONSchema = S.toJSONSchema
export var fromJSONSchema = S.fromJSONSchema
export var extendJSONSchema = S.extendJSONSchema
export var shape = S.shape
export var tuple = S.tuple
export var asyncDecoderAssert = S.js_asyncDecoderAssert
export var refine = S.js_refine
export var meta = S.meta
export var toExpression = S.toExpression
export var noValidation = S.noValidation
export var compile = S.compile
export var port = /*#__PURE__*/ S.port()
export var min = S.min
export var max = S.max
export var length = S.length
export var email = /*#__PURE__*/ S.email()
export var uuid = /*#__PURE__*/ S.uuid()
export var cuid = /*#__PURE__*/ S.cuid()
export var url = /*#__PURE__*/ S.url()
export var pattern = S.pattern
export var trim = S.trim
export var global = S.global
export var brand = S.brand
