// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let empty = [];

let Path = {
  empty: empty
};

let Exn = /* @__PURE__ */Primitive_exceptions.create("S.Exn");

Sury.$setExnId(Exn);

let none = 0;

let async = 1;

let Flag = {
  none: none,
  async: async
};

let $$Error = {};

function refine(schema, refiner, error, path) {
  return Sury.refine(schema, refiner, {
    error: error,
    path: path
  });
}

function unwrapConversion(conversion) {
  if (typeof conversion !== "object") {
    return conversion;
  } else if (conversion.TAG === "Sync") {
    return conversion._0;
  } else {
    return {
      async: conversion._0
    };
  }
}

function to(from, target, custom) {
  if (custom !== undefined) {
    return Sury.to(from, target, {
      decodeToOutput: unwrapConversion(custom.decode),
      encodeFromOutput: unwrapConversion(custom.encode)
    });
  } else {
    return Sury.to(from, target);
  }
}

function compileParse(to) {
  let fn = Sury.parser(to);
  return any => Sury.$safe(() => fn(any));
}

function compileParseAsync(to) {
  let fn = Sury.asyncParser(to);
  return any => Sury.$safeAsync(() => fn(any));
}

function compileConvertOrThrow(from, via, to) {
  if (via !== undefined) {
    return Sury.decoder(Sury.reverse(from), via, to);
  } else {
    return Sury.decoder(Sury.reverse(from), to);
  }
}

function compileConvertAsyncOrThrow(from, via, to) {
  if (via !== undefined) {
    return Sury.asyncDecoder(Sury.reverse(from), via, to);
  } else {
    return Sury.asyncDecoder(Sury.reverse(from), to);
  }
}

function compileConvert(from, via, to) {
  let fn = compileConvertOrThrow(from, via, to);
  return any => Sury.$safe(() => fn(any));
}

function compileConvertAsync(from, via, to) {
  let fn = compileConvertAsyncOrThrow(from, via, to);
  return any => Sury.$safeAsync(() => fn(any));
}

function compileMake(schema) {
  let fn = Sury.outputConstructor(schema);
  return value => Sury.$safe(() => fn(value));
}

function compileMakeAsync(schema) {
  let fn = Sury.asyncOutputConstructor(schema);
  return value => Sury.$safeAsync(() => fn(value));
}

function parseOrThrow(any, to) {
  return Sury.parser(to)(any);
}

function parseAsyncOrThrow(any, to) {
  return Sury.asyncParser(to)(any);
}

function parse(any, to) {
  return Sury.$safe(() => Sury.parser(to)(any));
}

function parseAsync(any, to) {
  return Sury.$safeAsync(() => Sury.asyncParser(to)(any));
}

function validate(any, to) {
  return Sury.inputValidator(to)(any);
}

function convertOrThrow(any, from, via, to) {
  return compileConvertOrThrow(from, via, to)(any);
}

function convertAsyncOrThrow(any, from, via, to) {
  return compileConvertAsyncOrThrow(from, via, to)(any);
}

function convert(any, from, via, to) {
  return Sury.$safe(() => convertOrThrow(any, from, via, to));
}

function convertAsync(any, from, via, to) {
  return Sury.$safeAsync(() => convertAsyncOrThrow(any, from, via, to));
}

function makeOrThrow(value, schema) {
  return Sury.outputConstructor(schema)(value);
}

function makeAsyncOrThrow(value, schema) {
  return Sury.asyncOutputConstructor(schema)(value);
}

function make(value, schema) {
  return Sury.$safe(() => Sury.outputConstructor(schema)(value));
}

function makeAsync(value, schema) {
  return Sury.$safeAsync(() => Sury.asyncOutputConstructor(schema)(value));
}

let Schema = {};

let $$Object = {};

let Tuple = {};

function tuple1(v0) {
  return Sury.tuple(s => s.item(0, v0));
}

function tuple2(v1, v2) {
  return Sury.schema([
    v1,
    v2
  ]);
}

function tuple3(v1, v2, v3) {
  return Sury.schema([
    v1,
    v2,
    v3
  ]);
}

let Option = {};

let Id = {};

let Metadata = {
  Id: Id
};

function fromJSONSchema(jsonSchema) {
  return Sury.fromJSONSchema(jsonSchema);
}

export {
  Path,
  Exn,
  Flag,
  $$Error,
  refine,
  to,
  compileParse,
  compileParseAsync,
  compileConvertOrThrow,
  compileConvertAsyncOrThrow,
  compileConvert,
  compileConvertAsync,
  compileMake,
  compileMakeAsync,
  parseOrThrow,
  parseAsyncOrThrow,
  parse,
  parseAsync,
  validate,
  convertOrThrow,
  convertAsyncOrThrow,
  convert,
  convertAsync,
  makeOrThrow,
  makeAsyncOrThrow,
  make,
  makeAsync,
  Schema,
  $$Object,
  Tuple,
  tuple1,
  tuple2,
  tuple3,
  Option,
  Metadata,
  fromJSONSchema,
}
/*  Not a pure module */
