// Generated by ReScript, PLEASE EDIT WITH CARE


let Issue = {};

function result(t) {
  if ((t.issues !== undefined)) {
    return {
      TAG: "Failure",
      _0: t
    };
  } else {
    return {
      TAG: "Success",
      _0: t
    };
  }
}

let Result = {
  result: result
};

let JsonSchema = {};

export {
  Issue,
  Result,
  JsonSchema,
}
/* No side effect */
