// @generated by protoc-gen-sury: the well-known types, as SuryProtobuf.
@@warning("-30")

let number = S.union([S.float, S.literal(Float.Constants.nan)])

// google/protobuf/any.proto

/**
 `Any` contains an arbitrary serialized protocol buffer message along with a
 URL that describes the type of the serialized message.

 In its binary encoding, an `Any` is an ordinary message; but in other wire
 forms like JSON, it has a special encoding. The format of the type URL is
 described on the `type_url` field.

 Protobuf APIs provide utilities to interact with `Any` values:

 - A 'pack' operation accepts a message and constructs a generic `Any` wrapper
   around it.
 - An 'unpack' operation reads the content of an `Any` message, either into an
   existing message or a new one. Unpack operations must check the type of the
   value they unpack against the declared `type_url`.
 - An 'is' operation decides whether an `Any` contains a message of the given
   type, i.e. whether it can 'unpack' that type.

 The JSON format representation of an `Any` follows one of these cases:

 - For types without special-cased JSON encodings, the JSON format
   representation of the `Any` is the same as that of the message, with an
   additional `@type` field which contains the type URL.
 - For types with special-cased JSON encodings (typically called 'well-known'
   types, listed in https://protobuf.dev/programming-guides/json/#any), the
   JSON format representation has a key `@type` which contains the type URL
   and a key `value` which contains the JSON-serialized value.

 The text format representation of an `Any` is like a message with one field
 whose name is the type URL in brackets. For example, an `Any` containing a
 `foo.Bar` message may be written `[type.googleapis.com/foo.Bar] { a: 2 }`.
 */
module Any = {
  type t = {
    /**
     Identifies the type of the serialized Protobuf message with a URI reference
     consisting of a prefix ending in a slash and the fully-qualified type name.

     Example: type.googleapis.com/google.protobuf.StringValue

     This string must contain at least one `/` character, and the content after
     the last `/` must be the fully-qualified name of the type in canonical
     form, without a leading dot. Do not write a scheme on these URI references
     so that clients do not attempt to contact them.

     The prefix is arbitrary and Protobuf implementations are expected to
     simply strip off everything up to and including the last `/` to identify
     the type. `type.googleapis.com/` is a common default prefix that some
     legacy implementations require. This prefix does not indicate the origin of
     the type, and URIs containing it are not expected to respond to any
     requests.

     All type URL strings must be legal URI references with the additional
     restriction (for the text format) that the content of the reference
     must consist only of alphanumeric characters, percent-encoded escapes, and
     characters in the following set (not including the outer backticks):
     `/-.~_!$&()*+,;=`. Despite our allowing percent encodings, implementations
     should not unescape them to prevent confusion with existing parsers. For
     example, `type.googleapis.com%2FFoo` should be rejected.

     In the original design of `Any`, the possibility of launching a type
     resolution service at these type URLs was considered but Protobuf never
     implemented one and considers contacting these URLs to be problematic and
     a potential security issue. Do not attempt to contact type URLs.
     */
    typeUrl: string,
    /**
     Holds a Protobuf serialization of the type described by type_url.
     */
    value: Uint8Array.t,
  }
  let schema: S.t<t> = S.schema(s => {
    typeUrl: s.matches(S.string->S.protobufField(1, ~type_=#string)),
    value: s.matches(S.uint8Array->S.protobufField(2, ~type_=#bytes)),
  })
}

// google/protobuf/source_context.proto

/**
 `SourceContext` represents information about the source of a
 protobuf element, like the file in which it is defined.
 */
module SourceContext = {
  type t = {
    /**
     The path-qualified name of the .proto file that contained the associated
     protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     */
    fileName: string,
  }
  let schema: S.t<t> = S.schema(s => {
    fileName: s.matches(S.string->S.protobufField(1, ~type_=#string)),
  })
}

// google/protobuf/type.proto

/**
 Basic field types.
 */
module Field_Kind = {
  type t = | @as(0) TypeUnknown | @as(1) TypeDouble | @as(2) TypeFloat | @as(3) TypeInt64 | @as(4) TypeUint64 | @as(5) TypeInt32 | @as(6) TypeFixed64 | @as(7) TypeFixed32 | @as(8) TypeBool | @as(9) TypeString | @as(10) TypeGroup | @as(11) TypeMessage | @as(12) TypeBytes | @as(13) TypeUint32 | @as(14) TypeEnum | @as(15) TypeSfixed32 | @as(16) TypeSfixed64 | @as(17) TypeSint32 | @as(18) TypeSint64
  let schema: S.t<t> = S.enum([TypeUnknown, TypeDouble, TypeFloat, TypeInt64, TypeUint64, TypeInt32, TypeFixed64, TypeFixed32, TypeBool, TypeString, TypeGroup, TypeMessage, TypeBytes, TypeUint32, TypeEnum, TypeSfixed32, TypeSfixed64, TypeSint32, TypeSint64])
}

/**
 Whether a field is optional, required, or repeated.
 */
module Field_Cardinality = {
  type t = | @as(0) Unknown | @as(1) Optional | @as(2) Required | @as(3) Repeated
  let schema: S.t<t> = S.enum([Unknown, Optional, Required, Repeated])
}

/**
 The syntax in which a protocol buffer element is defined.
 */
module Syntax = {
  type t = | @as(0) Proto2 | @as(1) Proto3 | @as(2) Editions
  let schema: S.t<t> = S.enum([Proto2, Proto3, Editions])
}

/**
 A protocol buffer option, which can be attached to a message, field,
 enumeration, etc.

 New usages of this message as an alternative to FileOptions, MessageOptions,
 FieldOptions, EnumOptions, EnumValueOptions, ServiceOptions, or MethodOptions
 are strongly discouraged.
 */
module Option = {
  type t = {
    /**
     The option's name. For protobuf built-in options (options defined in
     descriptor.proto), this is the short name. For example, `"map_entry"`.
     For custom options, it should be the fully-qualified name. For example,
     `"google.api.http"`.
     */
    name: string,
    /**
     The option's value packed in an Any message. If the value is a primitive,
     the corresponding wrapper type defined in google/protobuf/wrappers.proto
     should be used. If the value is an enum, it should be stored as an int32
     value using the google.protobuf.Int32Value type.
     */
    value: option<Any.t>,
  }
  let schema: S.t<t> = S.schema(s => {
    name: s.matches(S.string->S.protobufField(1, ~type_=#string)),
    value: s.matches(S.option(Any.schema)->S.protobufField(2, ~type_=#message)),
  })
}

/**
 A single field of a message type.

 New usages of this message as an alternative to FieldDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information.
 */
module Field = {
  type t = {
    /**
     The field type.
     */
    kind: Field_Kind.t,
    /**
     The field cardinality.
     */
    cardinality: Field_Cardinality.t,
    /**
     The field number.
     */
    number: int,
    /**
     The field name.
     */
    name: string,
    /**
     The field type URL, without the scheme, for message or enumeration
     types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
     */
    typeUrl: string,
    /**
     The index of the field type in `Type.oneofs`, for message or enumeration
     types. The first type has index 1; zero means the type is not in the list.
     */
    oneofIndex: int,
    /**
     Whether to use alternative packed wire representation.
     */
    packed: bool,
    /**
     The protocol buffer options.
     */
    options: array<Option.t>,
    /**
     The field JSON name.
     */
    jsonName: string,
    /**
     The string value of the default value of this field. Proto2 syntax only.
     */
    defaultValue: string,
  }
  let schema: S.t<t> = S.schema(s => {
    kind: s.matches(Field_Kind.schema->S.protobufField(1, ~type_=#enum)),
    cardinality: s.matches(Field_Cardinality.schema->S.protobufField(2, ~type_=#enum)),
    number: s.matches(S.int->S.protobufField(3, ~type_=#int32)),
    name: s.matches(S.string->S.protobufField(4, ~type_=#string)),
    typeUrl: s.matches(S.string->S.protobufField(6, ~type_=#string)),
    oneofIndex: s.matches(S.int->S.protobufField(7, ~type_=#int32)),
    packed: s.matches(S.bool->S.protobufField(8, ~type_=#bool)),
    options: s.matches(S.array(Option.schema)->S.protobufField(9, ~type_=#message)),
    jsonName: s.matches(S.string->S.protobufField(10, ~type_=#string)),
    defaultValue: s.matches(S.string->S.protobufField(11, ~type_=#string)),
  })
}

/**
 A protocol buffer message type.

 New usages of this message as an alternative to DescriptorProto are strongly
 discouraged. This message does not reliability preserve all information
 necessary to model the schema and preserve semantics. Instead make use of
 FileDescriptorSet which preserves the necessary information.
 */
module Type = {
  type t = {
    /**
     The fully qualified message name.
     */
    name: string,
    /**
     The list of fields.
     */
    fields: array<Field.t>,
    /**
     The list of types appearing in `oneof` definitions in this type.
     */
    oneofs: array<string>,
    /**
     The protocol buffer options.
     */
    options: array<Option.t>,
    /**
     The source context.
     */
    sourceContext: option<SourceContext.t>,
    /**
     The source syntax.
     */
    syntax: Syntax.t,
    /**
     The source edition string, only valid when syntax is SYNTAX_EDITIONS.
     */
    edition: string,
  }
  let schema: S.t<t> = S.schema(s => {
    name: s.matches(S.string->S.protobufField(1, ~type_=#string)),
    fields: s.matches(S.array(Field.schema)->S.protobufField(2, ~type_=#message)),
    oneofs: s.matches(S.array(S.string)->S.protobufField(3, ~type_=#string)),
    options: s.matches(S.array(Option.schema)->S.protobufField(4, ~type_=#message)),
    sourceContext: s.matches(S.option(SourceContext.schema)->S.protobufField(5, ~type_=#message)),
    syntax: s.matches(Syntax.schema->S.protobufField(6, ~type_=#enum)),
    edition: s.matches(S.string->S.protobufField(7, ~type_=#string)),
  })
}

/**
 Enum value definition.

 New usages of this message as an alternative to EnumValueDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information.
 */
module EnumValue = {
  type t = {
    /**
     Enum value name.
     */
    name: string,
    /**
     Enum value number.
     */
    number: int,
    /**
     Protocol buffer options.
     */
    options: array<Option.t>,
  }
  let schema: S.t<t> = S.schema(s => {
    name: s.matches(S.string->S.protobufField(1, ~type_=#string)),
    number: s.matches(S.int->S.protobufField(2, ~type_=#int32)),
    options: s.matches(S.array(Option.schema)->S.protobufField(3, ~type_=#message)),
  })
}

/**
 Enum type definition.

 New usages of this message as an alternative to EnumDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information.
 */
module Enum = {
  type t = {
    /**
     Enum type name.
     */
    name: string,
    /**
     Enum value definitions.
     */
    enumvalue: array<EnumValue.t>,
    /**
     Protocol buffer options.
     */
    options: array<Option.t>,
    /**
     The source context.
     */
    sourceContext: option<SourceContext.t>,
    /**
     The source syntax.
     */
    syntax: Syntax.t,
    /**
     The source edition string, only valid when syntax is SYNTAX_EDITIONS.
     */
    edition: string,
  }
  let schema: S.t<t> = S.schema(s => {
    name: s.matches(S.string->S.protobufField(1, ~type_=#string)),
    enumvalue: s.matches(S.array(EnumValue.schema)->S.protobufField(2, ~type_=#message)),
    options: s.matches(S.array(Option.schema)->S.protobufField(3, ~type_=#message)),
    sourceContext: s.matches(S.option(SourceContext.schema)->S.protobufField(4, ~type_=#message)),
    syntax: s.matches(Syntax.schema->S.protobufField(5, ~type_=#enum)),
    edition: s.matches(S.string->S.protobufField(6, ~type_=#string)),
  })
}

// google/protobuf/api.proto

/**
 Method represents a method of an API interface.

 New usages of this message as an alternative to MethodDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information.
 */
module Method = {
  type t = {
    /**
     The simple name of this method.
     */
    name: string,
    /**
     A URL of the input message type.
     */
    requestTypeUrl: string,
    /**
     If true, the request is streamed.
     */
    requestStreaming: bool,
    /**
     The URL of the output message type.
     */
    responseTypeUrl: string,
    /**
     If true, the response is streamed.
     */
    responseStreaming: bool,
    /**
     Any metadata attached to the method.
     */
    options: array<Option.t>,
    /**
     The source syntax of this method.

     This field should be ignored, instead the syntax should be inherited from
     Api. This is similar to Field and EnumValue.
     */
    syntax: Syntax.t,
    /**
     The source edition string, only valid when syntax is SYNTAX_EDITIONS.

     This field should be ignored, instead the edition should be inherited from
     Api. This is similar to Field and EnumValue.
     */
    edition: string,
  }
  let schema: S.t<t> = S.schema(s => {
    name: s.matches(S.string->S.protobufField(1, ~type_=#string)),
    requestTypeUrl: s.matches(S.string->S.protobufField(2, ~type_=#string)),
    requestStreaming: s.matches(S.bool->S.protobufField(3, ~type_=#bool)),
    responseTypeUrl: s.matches(S.string->S.protobufField(4, ~type_=#string)),
    responseStreaming: s.matches(S.bool->S.protobufField(5, ~type_=#bool)),
    options: s.matches(S.array(Option.schema)->S.protobufField(6, ~type_=#message)),
    syntax: s.matches(Syntax.schema->S.protobufField(7, ~type_=#enum)),
    edition: s.matches(S.string->S.protobufField(8, ~type_=#string)),
  })
}

/**
 Declares an API Interface to be included in this interface. The including
 interface must redeclare all the methods from the included interface, but
 documentation and options are inherited as follows:

 - If after comment and whitespace stripping, the documentation
   string of the redeclared method is empty, it will be inherited
   from the original method.

 - Each annotation belonging to the service config (http,
   visibility) which is not set in the redeclared method will be
   inherited.

 - If an http annotation is inherited, the path pattern will be
   modified as follows. Any version prefix will be replaced by the
   version of the including interface plus the [root][] path if
   specified.

 Example of a simple mixin:

     package google.acl.v1;
     service AccessControl {
       // Get the underlying ACL object.
       rpc GetAcl(GetAclRequest) returns (Acl) {
         option (google.api.http).get = "/v1/{resource=**}:getAcl";
       }
     }

     package google.storage.v2;
     service Storage {
       rpc GetAcl(GetAclRequest) returns (Acl);

       // Get a data record.
       rpc GetData(GetDataRequest) returns (Data) {
         option (google.api.http).get = "/v2/{resource=**}";
       }
     }

 Example of a mixin configuration:

     apis:
     - name: google.storage.v2.Storage
       mixins:
       - name: google.acl.v1.AccessControl

 The mixin construct implies that all methods in `AccessControl` are
 also declared with same name and request/response types in
 `Storage`. A documentation generator or annotation processor will
 see the effective `Storage.GetAcl` method after inheriting
 documentation and annotations as follows:

     service Storage {
       // Get the underlying ACL object.
       rpc GetAcl(GetAclRequest) returns (Acl) {
         option (google.api.http).get = "/v2/{resource=**}:getAcl";
       }
       ...
     }

 Note how the version in the path pattern changed from `v1` to `v2`.

 If the `root` field in the mixin is specified, it should be a
 relative path under which inherited HTTP paths are placed. Example:

     apis:
     - name: google.storage.v2.Storage
       mixins:
       - name: google.acl.v1.AccessControl
         root: acls

 This implies the following inherited HTTP annotation:

     service Storage {
       // Get the underlying ACL object.
       rpc GetAcl(GetAclRequest) returns (Acl) {
         option (google.api.http).get = "/v2/acls/{resource=**}:getAcl";
       }
       ...
     }
 */
module Mixin = {
  type t = {
    /**
     The fully qualified name of the interface which is included.
     */
    name: string,
    /**
     If non-empty specifies a path under which inherited HTTP paths
     are rooted.
     */
    root: string,
  }
  let schema: S.t<t> = S.schema(s => {
    name: s.matches(S.string->S.protobufField(1, ~type_=#string)),
    root: s.matches(S.string->S.protobufField(2, ~type_=#string)),
  })
}

/**
 Api is a light-weight descriptor for an API Interface.

 Interfaces are also described as "protocol buffer services" in some contexts,
 such as by the "service" keyword in a .proto file, but they are different
 from API Services, which represent a concrete implementation of an interface
 as opposed to simply a description of methods and bindings. They are also
 sometimes simply referred to as "APIs" in other contexts, such as the name of
 this message itself. See https://cloud.google.com/apis/design/glossary for
 detailed terminology.

 New usages of this message as an alternative to ServiceDescriptorProto are
 strongly discouraged. This message does not reliability preserve all
 information necessary to model the schema and preserve semantics. Instead
 make use of FileDescriptorSet which preserves the necessary information.
 */
module Api = {
  type t = {
    /**
     The fully qualified name of this interface, including package name
     followed by the interface's simple name.
     */
    name: string,
    /**
     The methods of this interface, in unspecified order.
     */
    methods: array<Method.t>,
    /**
     Any metadata attached to the interface.
     */
    options: array<Option.t>,
    /**
     A version string for this interface. If specified, must have the form
     `major-version.minor-version`, as in `1.10`. If the minor version is
     omitted, it defaults to zero. If the entire version field is empty, the
     major version is derived from the package name, as outlined below. If the
     field is not empty, the version in the package name will be verified to be
     consistent with what is provided here.

     The versioning schema uses [semantic
     versioning](http://semver.org) where the major version number
     indicates a breaking change and the minor version an additive,
     non-breaking change. Both version numbers are signals to users
     what to expect from different versions, and should be carefully
     chosen based on the product plan.

     The major version is also reflected in the package name of the
     interface, which must end in `v<major-version>`, as in
     `google.feature.v1`. For major versions 0 and 1, the suffix can
     be omitted. Zero major versions must only be used for
     experimental, non-GA interfaces.

     */
    version: string,
    /**
     Source context for the protocol buffer service represented by this
     message.
     */
    sourceContext: option<SourceContext.t>,
    /**
     Included interfaces. See [Mixin][].
     */
    mixins: array<Mixin.t>,
    /**
     The source syntax of the service.
     */
    syntax: Syntax.t,
    /**
     The source edition string, only valid when syntax is SYNTAX_EDITIONS.
     */
    edition: string,
  }
  let schema: S.t<t> = S.schema(s => {
    name: s.matches(S.string->S.protobufField(1, ~type_=#string)),
    methods: s.matches(S.array(Method.schema)->S.protobufField(2, ~type_=#message)),
    options: s.matches(S.array(Option.schema)->S.protobufField(3, ~type_=#message)),
    version: s.matches(S.string->S.protobufField(4, ~type_=#string)),
    sourceContext: s.matches(S.option(SourceContext.schema)->S.protobufField(5, ~type_=#message)),
    mixins: s.matches(S.array(Mixin.schema)->S.protobufField(6, ~type_=#message)),
    syntax: s.matches(Syntax.schema->S.protobufField(7, ~type_=#enum)),
    edition: s.matches(S.string->S.protobufField(8, ~type_=#string)),
  })
}

// google/protobuf/duration.proto

/**
 A Duration represents a signed, fixed-length span of time represented
 as a count of seconds and fractions of seconds at nanosecond
 resolution. It is independent of any calendar and concepts like "day"
 or "month". It is related to Timestamp in that the difference between
 two Timestamp values is a Duration and it can be added or subtracted
 from a Timestamp. Range is approximately +-10,000 years.

 # Examples

 Example 1: Compute Duration from two Timestamps in pseudo code.

     Timestamp start = ...;
     Timestamp end = ...;
     Duration duration = ...;

     duration.seconds = end.seconds - start.seconds;
     duration.nanos = end.nanos - start.nanos;

     if (duration.seconds < 0 && duration.nanos > 0) {
       duration.seconds += 1;
       duration.nanos -= 1000000000;
     } else if (duration.seconds > 0 && duration.nanos < 0) {
       duration.seconds -= 1;
       duration.nanos += 1000000000;
     }

 Example 2: Compute Timestamp from Timestamp + Duration in pseudo code.

     Timestamp start = ...;
     Duration duration = ...;
     Timestamp end = ...;

     end.seconds = start.seconds + duration.seconds;
     end.nanos = start.nanos + duration.nanos;

     if (end.nanos < 0) {
       end.seconds -= 1;
       end.nanos += 1000000000;
     } else if (end.nanos >= 1000000000) {
       end.seconds += 1;
       end.nanos -= 1000000000;
     }

 Example 3: Compute Duration from datetime.timedelta in Python.

     td = datetime.timedelta(days=3, minutes=10)
     duration = Duration()
     duration.FromTimedelta(td)

 # JSON Mapping

 In JSON format, the Duration type is encoded as a string rather than an
 object, where the string ends in the suffix "s" (indicating seconds) and
 is preceded by the number of seconds, with nanoseconds expressed as
 fractional seconds. For example, 3 seconds with 0 nanoseconds should be
 encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should
 be expressed in JSON format as "3.000000001s", and 3 seconds and 1
 microsecond should be expressed in JSON format as "3.000001s".

 */
module Duration = {
  type t = {
    /**
     Signed seconds of the span of time. Must be from -315,576,000,000
     to +315,576,000,000 inclusive. Note: these bounds are computed from:
     60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
     */
    seconds: bigint,
    /**
     Signed fractions of a second at nanosecond resolution of the span
     of time. Durations less than one second are represented with a 0
     `seconds` field and a positive or negative `nanos` field. For durations
     of one second or more, a non-zero value for the `nanos` field must be
     of the same sign as the `seconds` field. Must be from -999,999,999
     to +999,999,999 inclusive.
     */
    nanos: int,
  }
  let schema: S.t<t> = S.schema(s => {
    seconds: s.matches(S.bigint->S.protobufField(1, ~type_=#int64)),
    nanos: s.matches(S.int->S.protobufField(2, ~type_=#int32)),
  })
}

// google/protobuf/empty.proto

/**
 A generic empty message that you can re-use to avoid defining duplicated
 empty messages in your APIs. A typical example is to use it as the request
 or the response type of an API method. For instance:

     service Foo {
       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
     }

 */
module Empty = {
  type t
  let schema: S.t<t> = S.schema(_ => %raw(`{}`))
}

// google/protobuf/field_mask.proto

/**
 `FieldMask` represents a set of symbolic field paths, for example:

     paths: "f.a"
     paths: "f.b.d"

 Here `f` represents a field in some root message, `a` and `b`
 fields in the message found in `f`, and `d` a field found in the
 message in `f.b`.

 Field masks are used to specify a subset of fields that should be
 returned by a get operation or modified by an update operation.
 Field masks also have a custom JSON encoding (see below).

 # Field Masks in Projections

 When used in the context of a projection, a response message or
 sub-message is filtered by the API to only contain those fields as
 specified in the mask. For example, if the mask in the previous
 example is applied to a response message as follows:

     f {
       a : 22
       b {
         d : 1
         x : 2
       }
       y : 13
     }
     z: 8

 The result will not contain specific values for fields x,y and z
 (their value will be set to the default, and omitted in proto text
 output):


     f {
       a : 22
       b {
         d : 1
       }
     }

 A repeated field is not allowed except at the last position of a
 paths string.

 If a FieldMask object is not present in a get operation, the
 operation applies to all fields (as if a FieldMask of all fields
 had been specified).

 Note that a field mask does not necessarily apply to the
 top-level response message. In case of a REST get operation, the
 field mask applies directly to the response, but in case of a REST
 list operation, the mask instead applies to each individual message
 in the returned resource list. In case of a REST custom method,
 other definitions may be used. Where the mask applies will be
 clearly documented together with its declaration in the API.  In
 any case, the effect on the returned resource/resources is required
 behavior for APIs.

 # Field Masks in Update Operations

 A field mask in update operations specifies which fields of the
 targeted resource are going to be updated. The API is required
 to only change the values of the fields as specified in the mask
 and leave the others untouched. If a resource is passed in to
 describe the updated values, the API ignores the values of all
 fields not covered by the mask.

 If a repeated field is specified for an update operation, new values will
 be appended to the existing repeated field in the target resource. Note that
 a repeated field is only allowed in the last position of a `paths` string.

 If a sub-message is specified in the last position of the field mask for an
 update operation, then new value will be merged into the existing sub-message
 in the target resource.

 For example, given the target message:

     f {
       b {
         d: 1
         x: 2
       }
       c: [1]
     }

 And an update message:

     f {
       b {
         d: 10
       }
       c: [2]
     }

 then if the field mask is:

  paths: ["f.b", "f.c"]

 then the result will be:

     f {
       b {
         d: 10
         x: 2
       }
       c: [1, 2]
     }

 An implementation may provide options to override this default behavior for
 repeated and message fields.

 Note that libraries which implement FieldMask resolution have various
 different behaviors in the face of empty masks or the special "*" mask.
 When implementing a service you should confirm these cases have the
 appropriate behavior in the underlying FieldMask library that you desire,
 and you may need to special case those cases in your application code if
 the underlying field mask library behavior differs from your intended
 service semantics.

 Update methods implementing https://google.aip.dev/134
 - MUST support the special value * meaning "full replace"
 - MUST treat an omitted field mask as "replace fields which are present".

 Other methods implementing https://google.aip.dev/157
 - SHOULD support the special value "*" to mean "get all".
 - MUST treat an omitted field mask to mean "get all", unless otherwise
 documented.

 ## Considerations for HTTP REST

 The HTTP kind of an update operation which uses a field mask must
 be set to PATCH instead of PUT in order to satisfy HTTP semantics
 (PUT must only be used for full updates).

 # JSON Encoding of Field Masks

 In JSON, a field mask is encoded as a single string where paths are
 separated by a comma. Fields name in each path are converted
 to/from lower-camel naming conventions.

 As an example, consider the following message declarations:

     message Profile {
       User user = 1;
       Photo photo = 2;
     }
     message User {
       string display_name = 1;
       string address = 2;
     }

 In proto a field mask for `Profile` may look as such:

     mask {
       paths: "user.display_name"
       paths: "photo"
     }

 In JSON, the same mask is represented as below:

     {
       mask: "user.displayName,photo"
     }

 # Field Masks and Oneof Fields

 Field masks treat fields in oneofs just as regular fields. Consider the
 following message:

     message SampleMessage {
       oneof test_oneof {
         string name = 4;
         SubMessage sub_message = 9;
       }
     }

 The field mask can be:

     mask {
       paths: "name"
     }

 Or:

     mask {
       paths: "sub_message"
     }

 Note that oneof type names ("test_oneof" in this case) cannot be used in
 paths.

 ## Field Mask Verification

 The implementation of any API method which has a FieldMask type field in the
 request should verify the included field paths, and return an
 `INVALID_ARGUMENT` error if any path is unmappable.
 */
module FieldMask = {
  type t = {
    /**
     The set of field mask paths.
     */
    paths: array<string>,
  }
  let schema: S.t<t> = S.schema(s => {
    paths: s.matches(S.array(S.string)->S.protobufField(1, ~type_=#string)),
  })
}

// google/protobuf/struct.proto

/**
 Represents a JSON `null`.

 `NullValue` is a sentinel, using an enum with only one value to represent
 the null value for the `Value` type union.

 A field of type `NullValue` with any value other than `0` is considered
 invalid. Most ProtoJSON serializers will emit a Value with a `null_value` set
 as a JSON `null` regardless of the integer value, and so will round trip to
 a `0` value.
 */
module NullValue = {
  type t = | @as(0) NullValue
  let schema: S.t<t> = S.enum([NullValue])
}

type rec struct = {
  /**
   Unordered map of dynamically typed values.
   */
  fields: dict<value>,
}
@tag("case")
and value_kind =
  | @as("nullValue") NullValue({value: NullValue.t})
  | @as("numberValue") NumberValue({value: float})
  | @as("stringValue") StringValue({value: string})
  | @as("boolValue") BoolValue({value: bool})
  | @as("structValue") StructValue({value: struct})
  | @as("listValue") ListValue({value: listValue})
and value = {
  kind: option<value_kind>,
}
and listValue = {
  /**
   Repeated field of dynamically typed values.
   */
  values: array<value>,
}

/**
 Represents a JSON object.

 An unordered key-value map, intending to perfectly capture the semantics of a
 JSON object. This enables parsing any arbitrary JSON payload as a message
 field in ProtoJSON format.

 This follows RFC 8259 guidelines for interoperable JSON: notably this type
 cannot represent large Int64 values or `NaN`/`Infinity` numbers,
 since the JSON format generally does not support those values in its number
 type.

 If you do not intend to parse arbitrary JSON into your message, a custom
 typed message should be preferred instead of using this type.
 */
module Struct = {
  type t = struct
  let schema: S.t<t> = S.recursive("Struct", self =>
    S.schema(s => {
      fields: s.matches(S.dict(S.recursive("Value", (self2: S.t<value>) =>
      S.schema(s => {
        kind: s.matches(S.option(
          S.union([
            S.schema(s => NullValue({value: s.matches(NullValue.schema->S.protobufField(1, ~type_=#enum))})),
            S.schema(s => NumberValue({value: s.matches(number->S.protobufField(2, ~type_=#double))})),
            S.schema(s => StringValue({value: s.matches(S.string->S.protobufField(3, ~type_=#string))})),
            S.schema(s => BoolValue({value: s.matches(S.bool->S.protobufField(4, ~type_=#bool))})),
            S.schema(s => StructValue({value: s.matches(self->S.protobufField(5, ~type_=#message))})),
            S.schema(s => ListValue({value: s.matches(S.recursive("ListValue", (_self3: S.t<listValue>) =>
        S.schema(s => {
          values: s.matches(S.array(self2)->S.protobufField(1, ~type_=#message)),
        })
      )->S.protobufField(6, ~type_=#message))})),
          ]),
        )),
      })
    ))->S.protobufField(1, ~type_=#message, ~key=#string)),
    })
  )
}

/**
 Represents a JSON value.

 `Value` represents a dynamically typed value which can be either
 null, a number, a string, a boolean, a recursive struct value, or a
 list of values. A producer of value is expected to set one of these
 variants. Absence of any variant is an invalid state.
 */
module Value = {
  type t = value
  let schema: S.t<t> = S.recursive("Value", self =>
    S.schema(s => {
      kind: s.matches(S.option(
        S.union([
          S.schema(s => NullValue({value: s.matches(NullValue.schema->S.protobufField(1, ~type_=#enum))})),
          S.schema(s => NumberValue({value: s.matches(number->S.protobufField(2, ~type_=#double))})),
          S.schema(s => StringValue({value: s.matches(S.string->S.protobufField(3, ~type_=#string))})),
          S.schema(s => BoolValue({value: s.matches(S.bool->S.protobufField(4, ~type_=#bool))})),
          S.schema(s => StructValue({value: s.matches(S.recursive("Struct", (_self2: S.t<struct>) =>
      S.schema(s => {
        fields: s.matches(S.dict(self)->S.protobufField(1, ~type_=#message, ~key=#string)),
      })
    )->S.protobufField(5, ~type_=#message))})),
          S.schema(s => ListValue({value: s.matches(S.recursive("ListValue", (_self2: S.t<listValue>) =>
      S.schema(s => {
        values: s.matches(S.array(self)->S.protobufField(1, ~type_=#message)),
      })
    )->S.protobufField(6, ~type_=#message))})),
        ]),
      )),
    })
  )
}

/**
 Represents a JSON array.
 */
module ListValue = {
  type t = listValue
  let schema: S.t<t> = S.recursive("ListValue", self =>
    S.schema(s => {
      values: s.matches(S.array(S.recursive("Value", (self2: S.t<value>) =>
      S.schema(s => {
        kind: s.matches(S.option(
          S.union([
            S.schema(s => NullValue({value: s.matches(NullValue.schema->S.protobufField(1, ~type_=#enum))})),
            S.schema(s => NumberValue({value: s.matches(number->S.protobufField(2, ~type_=#double))})),
            S.schema(s => StringValue({value: s.matches(S.string->S.protobufField(3, ~type_=#string))})),
            S.schema(s => BoolValue({value: s.matches(S.bool->S.protobufField(4, ~type_=#bool))})),
            S.schema(s => StructValue({value: s.matches(S.recursive("Struct", (_self3: S.t<struct>) =>
        S.schema(s => {
          fields: s.matches(S.dict(self2)->S.protobufField(1, ~type_=#message, ~key=#string)),
        })
      )->S.protobufField(5, ~type_=#message))})),
            S.schema(s => ListValue({value: s.matches(self->S.protobufField(6, ~type_=#message))})),
          ]),
        )),
      })
    ))->S.protobufField(1, ~type_=#message)),
    })
  )
}

// google/protobuf/timestamp.proto

/**
 A Timestamp represents a point in time independent of any time zone or local
 calendar, encoded as a count of seconds and fractions of seconds at
 nanosecond resolution. The count is relative to an epoch at UTC midnight on
 January 1, 1970, in the proleptic Gregorian calendar which extends the
 Gregorian calendar backwards to year one.

 All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
 second table is needed for interpretation, using a [24-hour linear
 smear](https://developers.google.com/time/smear).

 The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
 restricting to that range, we ensure that we can convert to and from [RFC
 3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

 # Examples

 Example 1: Compute Timestamp from POSIX `time()`.

     Timestamp timestamp;
     timestamp.set_seconds(time(NULL));
     timestamp.set_nanos(0);

 Example 2: Compute Timestamp from POSIX `gettimeofday()`.

     struct timeval tv;
     gettimeofday(&tv, NULL);

     Timestamp timestamp;
     timestamp.set_seconds(tv.tv_sec);
     timestamp.set_nanos(tv.tv_usec * 1000);

 Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

     FILETIME ft;
     GetSystemTimeAsFileTime(&ft);
     UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

     // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
     // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
     Timestamp timestamp;
     timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
     timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

 Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

     long millis = System.currentTimeMillis();

     Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
         .setNanos((int) ((millis % 1000) * 1000000)).build();

 Example 5: Compute Timestamp from Java `Instant.now()`.

     Instant now = Instant.now();

     Timestamp timestamp =
         Timestamp.newBuilder().setSeconds(now.getEpochSecond())
             .setNanos(now.getNano()).build();

 Example 6: Compute Timestamp from current time in Python.

     timestamp = Timestamp()
     timestamp.GetCurrentTime()

 # JSON Mapping

 In JSON format, the Timestamp type is encoded as a string in the
 [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
 format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
 where {year} is always expressed using four digits while {month}, {day},
 {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
 seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
 are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
 is required. A ProtoJSON serializer should always use UTC (as indicated by
 "Z") when printing the Timestamp type and a ProtoJSON parser should be
 able to accept both UTC and other timezones (as indicated by an offset).

 For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
 01:30 UTC on January 15, 2017.

 In JavaScript, one can convert a Date object to this format using the
 standard
 [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
 method. In Python, a standard `datetime.datetime` object can be converted
 to this format using
 [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
 the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
 the Joda Time's [`ISODateTimeFormat.dateTime()`](
 http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
 ) to obtain a formatter capable of generating timestamps in this format.

 */
module Timestamp = {
  type t = {
    /**
     Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must
     be between -62135596800 and 253402300799 inclusive (which corresponds to
     0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z).
     */
    seconds: bigint,
    /**
     Non-negative fractions of a second at nanosecond resolution. This field is
     the nanosecond portion of the duration, not an alternative to seconds.
     Negative second values with fractions must still have non-negative nanos
     values that count forward in time. Must be between 0 and 999,999,999
     inclusive.
     */
    nanos: int,
  }
  let schema: S.t<t> = S.schema(s => {
    seconds: s.matches(S.bigint->S.protobufField(1, ~type_=#int64)),
    nanos: s.matches(S.int->S.protobufField(2, ~type_=#int32)),
  })
}

// google/protobuf/wrappers.proto

/**
 Wrapper message for `double`.

 The JSON representation for `DoubleValue` is JSON number.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module DoubleValue = {
  type t = {
    /**
     The double value.
     */
    value: float,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(number->S.protobufField(1, ~type_=#double)),
  })
}

/**
 Wrapper message for `float`.

 The JSON representation for `FloatValue` is JSON number.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module FloatValue = {
  type t = {
    /**
     The float value.
     */
    value: float,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(number->S.protobufField(1, ~type_=#float)),
  })
}

/**
 Wrapper message for `int64`.

 The JSON representation for `Int64Value` is JSON string.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module Int64Value = {
  type t = {
    /**
     The int64 value.
     */
    value: bigint,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(S.bigint->S.protobufField(1, ~type_=#int64)),
  })
}

/**
 Wrapper message for `uint64`.

 The JSON representation for `UInt64Value` is JSON string.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module UInt64Value = {
  type t = {
    /**
     The uint64 value.
     */
    value: bigint,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(S.bigint->S.protobufField(1, ~type_=#uint64)),
  })
}

/**
 Wrapper message for `int32`.

 The JSON representation for `Int32Value` is JSON number.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module Int32Value = {
  type t = {
    /**
     The int32 value.
     */
    value: int,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(S.int->S.protobufField(1, ~type_=#int32)),
  })
}

/**
 Wrapper message for `uint32`.

 The JSON representation for `UInt32Value` is JSON number.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module UInt32Value = {
  type t = {
    /**
     The uint32 value.
     */
    value: S.integer,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(S.integer->S.protobufField(1, ~type_=#uint32)),
  })
}

/**
 Wrapper message for `bool`.

 The JSON representation for `BoolValue` is JSON `true` and `false`.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module BoolValue = {
  type t = {
    /**
     The bool value.
     */
    value: bool,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(S.bool->S.protobufField(1, ~type_=#bool)),
  })
}

/**
 Wrapper message for `string`.

 The JSON representation for `StringValue` is JSON string.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module StringValue = {
  type t = {
    /**
     The string value.
     */
    value: string,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(S.string->S.protobufField(1, ~type_=#string)),
  })
}

/**
 Wrapper message for `bytes`.

 The JSON representation for `BytesValue` is JSON string.

 Not recommended for use in new APIs, but still useful for legacy APIs and
 has no plan to be removed.
 */
module BytesValue = {
  type t = {
    /**
     The bytes value.
     */
    value: Uint8Array.t,
  }
  let schema: S.t<t> = S.schema(s => {
    value: s.matches(S.uint8Array->S.protobufField(1, ~type_=#bytes)),
  })
}
