// Generates `sury/wkt` - the well-known types a generated file imports rather
// than expecting beside it - from the upstream protos buf ships, with this
// generator. The output is committed; `test/cli.ts` fails when it is stale.
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { decodeFileDescriptorSet } from "../src/descriptor";
import { generate } from "../src/plugin";
import { buildRegistry } from "../src/model";
import { numberDecl, resModules, wktModule, moduleOf } from "../src/res";
import { wktFiles } from "../src/shared";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const buf = join(root, "node_modules/.bin/buf");

export const wktSet = () => {
  const dir = mkdtempSync(join(tmpdir(), "sury-wkt-"));
  try {
    writeFileSync(join(dir, "buf.yaml"), "version: v2\n");
    writeFileSync(join(dir, "wkt.proto"), `syntax = "proto3";\n${[...wktFiles].map((file) => `import "${file}";\n`).join("")}`);
    execFileSync(buf, ["build", dir, "-o", join(dir, "set.binpb")], { stdio: ["ignore", "ignore", "inherit"] });
    return decodeFileDescriptorSet(new Uint8Array(readFileSync(join(dir, "set.binpb"))));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
};

// What `sury/wkt` exports: every generated file, and the JSON types a Struct
// field is held as.
export const wktIndex = (): string =>
  [
    "// @generated by protoc-gen-sury: the well-known types, as `sury/wkt`.",
    "/* eslint-disable */",
    "",
    'import type * as S from "sury";',
    "",
    ...[...wktFiles].map((file) => `export * from "./${file.replace(/\.proto$/, "_pb.js")}";`),
    "",
    "/** A JSON value, what a `google.protobuf.Value` holds. */",
    "export type JsonValue = S.Infer<typeof S.json>;",
    "",
    "/** A JSON object: how a `google.protobuf.Struct` field is held. */",
    "export type JsonObject = { [key: string]: JsonValue };",
    "",
  ].join("\n");

export const generateWkt = (): { name: string; content: string }[] => {
  const set = wktSet();
  const response = generate({ fileToGenerate: [...wktFiles], parameter: "target=ts,import_extension=js", protoFile: set.file }, "");
  if (response.error !== undefined) throw new Error(response.error);
  return [...response.file, { name: "index.ts", content: wktIndex() }];
};

// The same types for ReScript, as one module beside S.res: every well-known
// type file in dependency order, each type a module of its own.
export const generateWktRes = (): string => {
  const set = wktSet();
  const registry = buildRegistry(set.file);
  const ordered: string[] = [];
  const visit = (name: string) => {
    if (ordered.includes(name) || !wktFiles.has(name)) return;
    for (const dependency of registry.files.get(name)!.proto.dependency) visit(dependency);
    ordered.push(name);
  };
  for (const name of wktFiles) visit(name);
  let usesNumber = false;
  const bodies = ordered.map((name) => {
    const result = resModules(registry.files.get(name)!, { s: "S.", wkt: (desc) => moduleOf(desc) });
    usesNumber ||= result.usesNumber;
    return `// ${name}\n\n${result.body}`;
  });
  return (
    `// @generated by protoc-gen-sury: the well-known types, as ${wktModule}.\n` +
    `@@warning("-30")\n\n${usesNumber ? `${numberDecl("S.")}\n` : ""}${bodies.join("\n")}`
  );
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(root, `../sury/src/${wktModule}.res`), generateWktRes());
  const out = join(root, "../sury/src/wkt");
  rmSync(out, { recursive: true, force: true });
  for (const file of generateWkt()) {
    mkdirSync(dirname(join(out, file.name)), { recursive: true });
    writeFileSync(join(out, file.name), file.content);
  }
}
