// Harness SUBJECT half: canonicalize specs, (re)compute goldens by executing the
// real schema, and expand a spec into a Vitest file.
//
// Unlike format.ts (which runs on published sury), this half imports the
// in-development sury SOURCE (`../sury/src/S.js`), because goldens must reflect
// the code under test — that's how `spec check`/`update` catch codegen changes.
//
// Generated test files are NOT committed (gitignored, regenerated by sury's
// `pretest`); the committed record of generation is the snapshot in
// packages/sury/tests/spec_test.ts.
import { readFileSync, readdirSync } from "node:fs";
import { join, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import * as S from "../sury/src/S.js";
import {
  KEY_ORDER,
  TS_KEY_ORDER,
  OP_ORDER,
  isSkip,
  type Spec,
  type Operation,
  type Example,
  type OpName,
} from "./format";
import { deriveTypeInfo } from "./introspect";

const here = (rel: string) => fileURLToPath(new URL(rel, import.meta.url));
// The spec suite lives in the sury package (specs ship with it).
export const SPECS_DIR = here("../sury/specs/");
export const GEN_DIR = here("../sury/tests/generated/");
export const SCHEMA_PATH = join(SPECS_DIR, "spec.schema.json");

const HEADER = "# yaml-language-server: $schema=./spec.schema.json";

// Maps an operation to the dev-sury builder that compiles that direction.
const OP_BUILDER: Record<OpName, (schema: any) => (input: any) => any> = {
  parse: S.parser,
  decode: S.decoder,
  encode: S.encoder,
};

// The reason string on a `_skip` must be a known enum value or `todo(#…)`.
// (`identity` isn't here — it's no longer a `_skip` reason, see Operation.)
const SKIP_REASONS = new Set([
  "parser-only",
  "serializer-only",
  "lossy",
  "not-applicable",
]);
export const isValidSkipReason = (r: unknown): boolean =>
  typeof r === "string" && (SKIP_REASONS.has(r) || /^todo\(#.+\)$/.test(r));

export const specId = (file: string): string =>
  basename(file).replace(/\.yaml$/, "");

export const listSpecFiles = (): string[] =>
  readdirSync(SPECS_DIR)
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => join(SPECS_DIR, f))
    .sort();

export const readSpec = (file: string): Spec =>
  parseYaml(readFileSync(file, "utf8")) as Spec;

export const evalSchema = (tsSource: string): any =>
  new Function("S", `return (${tsSource});`)(S);

// Sury compiles a pass-through operation to this shared function — the ONLY
// signal identity detection has. If this name is ever changed in Sury's
// source, every `identity`-marked operation starts failing loudly (across
// every spec, in `identityViolations` below) rather than silently going stale.
const NOOP_OPERATION_WHICH_WILL_NEVER_CHANGE = "noopOperation";
const isNoop = (fn: Function): boolean =>
  fn.name === NOOP_OPERATION_WHICH_WILL_NEVER_CHANGE;

// Enforce the identity invariant both ways: an operation compiles to Sury's
// pass-through *iff* it is declared the literal `identity`. Returns violation
// messages ([] if ok). Requires the live (dev) schema.
export const identityViolations = (schema: any, spec: Spec): string[] => {
  const out: string[] = [];
  for (const opName of OP_ORDER) {
    const op = spec.operations[opName];
    const noop = isNoop(OP_BUILDER[opName](schema));
    if (op === "identity") {
      if (!noop)
        out.push(
          `operations.${opName}: marked \`identity\` but does not compile to identity — use a full op block with examples`,
        );
    } else if (noop) {
      out.push(
        `operations.${opName}: compiles to identity — use \`identity\` instead of an expression + examples`,
      );
    }
  }
  return out;
};

// Fully derive the jsonSchema dimension from a live schema — no example inputs
// needed, so `spec new` can fill this in immediately from `--ts`.
export const scaffoldJsonSchema = (schema: any) => ({
  input: asJson(S.toJSONSchema(schema)),
  output: asJson(S.toJSONSchema(S.reverse(schema))),
});

// Fully derive the operations dimension from a live schema: an identity op
// collapses to the literal `identity`; others get their expression golden with
// no examples yet (the author still adds example inputs by hand).
export const scaffoldOperations = (schema: any): Spec["operations"] =>
  Object.fromEntries(
    OP_ORDER.map((opName) => {
      const fn = OP_BUILDER[opName](schema);
      const op: Operation = isNoop(fn)
        ? "identity"
        : { expression: fn.toString(), examples: {} };
      return [opName, op];
    }),
  ) as Spec["operations"];

// ---- canonical form -------------------------------------------------------

const order = <T extends Record<string, unknown>>(obj: T, keys: string[]): T => {
  if (obj === null || typeof obj !== "object" || Array.isArray(obj)) return obj;
  const out: Record<string, unknown> = {};
  for (const k of keys) if (k in obj) out[k] = obj[k];
  for (const k of Object.keys(obj)) if (!(k in out)) out[k] = obj[k];
  return out as T;
};

// Individual named examples are never `_skip` — only the enclosing operation
// block is (the format schema has no `orSkip` on the examples map's values).
const canonExample = (ex: Example): Example =>
  order(ex, ["input", "output", "error", "bench"]) as Example;

const canonOp = (op: Operation): Operation => {
  if (op === "identity") return op;
  const o = order(op, ["expression", "examples"]);
  if (o.examples && typeof o.examples === "object") {
    const ex: Record<string, Example> = {};
    for (const [name, v] of Object.entries(o.examples)) ex[name] = canonExample(v);
    o.examples = ex;
  }
  return o;
};

export const canonicalize = (obj: Spec): Spec => {
  const o = order(obj, KEY_ORDER as string[]);
  if (o.ts) o.ts = order(o.ts, TS_KEY_ORDER as string[]);
  if (o.jsonSchema && !isSkip(o.jsonSchema))
    o.jsonSchema = order(o.jsonSchema as Record<string, unknown>, [
      "input",
      "output",
    ]) as Spec["jsonSchema"];
  if (o.operations) {
    const ops = order(o.operations, OP_ORDER);
    for (const name of OP_ORDER) if (ops[name]) ops[name] = canonOp(ops[name]);
    o.operations = ops;
  }
  return o;
};

export const serialize = (obj: Spec): string =>
  HEADER + "\n" + stringifyYaml(canonicalize(obj), { lineWidth: 0 });

// ---- golden recomputation (golden-master `update`) ------------------------

const inlineToValue = (codeStr: string): unknown =>
  new Function("S", `return (${codeStr});`)(S);

// `S.toJSONSchema` returns the concrete `JSONSchema7` interface, which has no
// index signature and so doesn't structurally satisfy Sury's generic `JSON`
// type — even though every JSONSchema7 value is valid JSON data. Bridge the
// two Sury-internal type declarations at this one boundary.
const asJson = (v: unknown): S.Output<typeof S.json> => v as S.Output<typeof S.json>;

const valueToCode = (v: unknown): string =>
  typeof v === "string" || (typeof v === "object" && v !== null)
    ? JSON.stringify(v)
    : String(v);

const clean = <T extends Record<string, unknown>>(o: T): T => {
  const r: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(o)) if (v !== undefined) r[k] = v;
  return r as T;
};

// Recompute everything derivable from the live (dev) schema: per-op codegen
// goldens, input/output JSON Schemas, ts.input/ts.output/ts.instantiations (via
// introspect.ts), and each example's result by running the operation. The
// author owns inputs and skips (and can still `_skip` any of these — e.g.
// `ts.instantiations: { _skip: not-applicable }`); the harness owns the
// answers. (`ts.bundleBytes` is NOT recomputed here — awaiting a harness
// feature that doesn't exist yet; see Spec Harness Suggestions.)
export const recomputeGoldens = (obj: Spec): Spec => {
  const next: Spec = structuredClone(obj);
  const schema = evalSchema(next.ts.schema);

  if (!isSkip(next.ts.input) || !isSkip(next.ts.output) || !isSkip(next.ts.instantiations)) {
    const info = deriveTypeInfo(next.ts.schema);
    if (!isSkip(next.ts.input)) next.ts.input = info.input;
    if (!isSkip(next.ts.output)) next.ts.output = info.output;
    if (!isSkip(next.ts.instantiations)) next.ts.instantiations = info.instantiations;
  }

  if (!isSkip(next.jsonSchema)) {
    next.jsonSchema = {
      input: asJson(S.toJSONSchema(schema)),
      output: asJson(S.toJSONSchema(S.reverse(schema))),
    };
  }

  for (const opName of OP_ORDER) {
    const op = next.operations[opName];
    if (op === "identity") continue;
    const fn = OP_BUILDER[opName](schema);
    if (!isSkip(op.expression)) op.expression = fn.toString();
    for (const [name, ex] of Object.entries(op.examples)) {
      const bench = ex.bench;
      try {
        const out = fn(inlineToValue(ex.input));
        op.examples[name] = clean({ input: ex.input, output: valueToCode(out), bench });
      } catch (e) {
        op.examples[name] = clean({ input: ex.input, error: (e as Error).message, bench });
      }
    }
  }
  return next;
};

// ---- test-file generation -------------------------------------------------

const lit = (s: string): string => JSON.stringify(s);

const runner = (opName: OpName): string =>
  `S.${opName === "parse" ? "parser" : opName === "decode" ? "decoder" : "encoder"}(schema)`;

export const generateTest = (id: string, obj: Spec): string => {
  const L: string[] = [];
  L.push(`// @generated from specs/${id}.yaml — DO NOT EDIT. Regenerate: pnpm spec gen`);
  L.push(`import { test, expect, expectTypeOf } from "vitest";`);
  L.push(`import * as S from "../../src/S.js";`);
  L.push(``);
  L.push(`const schema = ${obj.ts.schema};`);
  L.push(``);

  if (!isSkip(obj.ts.output)) {
    L.push(`test(${lit(`${id} › ts › output`)}, () => {`);
    L.push(
      `  expectTypeOf<S.Output<typeof schema>>().toEqualTypeOf<${obj.ts.output}>();`,
    );
    L.push(`});`);
  }
  if (!isSkip(obj.ts.input)) {
    L.push(`test(${lit(`${id} › ts › input`)}, () => {`);
    L.push(
      `  expectTypeOf<S.Input<typeof schema>>().toEqualTypeOf<${obj.ts.input}>();`,
    );
    L.push(`});`);
  }

  if (!isSkip(obj.jsonSchema)) {
    const js = obj.jsonSchema as { input: unknown; output: unknown };
    L.push(`test(${lit(`${id} › jsonSchema`)}, () => {`);
    L.push(`  expect(S.toJSONSchema(schema)).toStrictEqual(${JSON.stringify(js.input)});`);
    L.push(
      `  expect(S.toJSONSchema(S.reverse(schema))).toStrictEqual(${JSON.stringify(js.output)});`,
    );
    L.push(`});`);
  }

  for (const opName of OP_ORDER) {
    const op = obj.operations[opName];
    if (op === "identity") continue;
    const run = runner(opName);
    if (!isSkip(op.expression)) {
      L.push(`test(${lit(`${id} › ${opName} › expression`)}, () => {`);
      L.push(`  expect(${run}.toString()).toBe(${lit(op.expression)});`);
      L.push(`});`);
    }
    for (const [name, ex] of Object.entries(op.examples)) {
      L.push(`test(${lit(`${id} › ${opName} › ${name}`)}, () => {`);
      if ("error" in ex) {
        L.push(`  expect(() => ${run}(${ex.input})).toThrow(${lit(ex.error)});`);
      } else {
        L.push(`  expect(${run}(${ex.input})).toStrictEqual(${ex.output});`);
      }
      L.push(`});`);
    }
  }
  return L.join("\n") + "\n";
};

export const genPath = (id: string): string => join(GEN_DIR, `${id}.gen_test.ts`);

// Re-exported so `spec new` can populate ts.input/ts.output/ts.instantiations
// up front too (cli.ts only imports from harness.ts/format.ts, never touches
// introspect.ts directly).
export { deriveTypeInfo, type TypeInfo } from "./introspect";
