// @generated by protoc-gen-sury: the well-known types, as `sury/wkt`.
/* eslint-disable */

import type * as S from "sury";

export * from "./google/protobuf/any_pb.js";
export * from "./google/protobuf/api_pb.js";
export * from "./google/protobuf/duration_pb.js";
export * from "./google/protobuf/empty_pb.js";
export * from "./google/protobuf/field_mask_pb.js";
export * from "./google/protobuf/source_context_pb.js";
export * from "./google/protobuf/struct_pb.js";
export * from "./google/protobuf/timestamp_pb.js";
export * from "./google/protobuf/type_pb.js";
export * from "./google/protobuf/wrappers_pb.js";

/** A JSON value, what a `google.protobuf.Value` holds. */
export type JsonValue = S.Infer<typeof S.json>;

/** A JSON object: how a `google.protobuf.Struct` field is held. */
export type JsonObject = { [key: string]: JsonValue };
