// @generated by protoc-gen-sury with parameter "target=ts,import_extension=js"
// @generated from file google/protobuf/source_context.proto (package google.protobuf, syntax proto3)
/* eslint-disable */

import * as S from "sury";

/**
 * `SourceContext` represents information about the source of a
 * protobuf element, like the file in which it is defined.
 *
 * @generated from message google.protobuf.SourceContext
 */
export type SourceContext = {
  /**
   * The path-qualified name of the .proto file that contained the associated
   * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
   *
   * @generated from field: string file_name = 1;
   */
  fileName: string;
};

export const SourceContextSchema = S.meta(/* @__PURE__ */ S.schemaOf<SourceContext>()({
  fileName: S.protobufField(S.string, { number: 1, type: "string" }),
}), { name: "SourceContext" });
