// @generated by protoc-gen-sury with parameter "target=ts,import_extension=js"
// @generated from file google/protobuf/struct.proto (package google.protobuf, syntax proto3)
/* eslint-disable */

import * as S from "sury";

const $number = S.union([S.number, S.schema(NaN)]);

/**
 * Represents a JSON `null`.
 *
 * `NullValue` is a sentinel, using an enum with only one value to represent
 * the null value for the `Value` type union.
 *
 * A field of type `NullValue` with any value other than `0` is considered
 * invalid. Most ProtoJSON serializers will emit a Value with a `null_value` set
 * as a JSON `null` regardless of the integer value, and so will round trip to
 * a `0` value.
 *
 * @generated from enum google.protobuf.NullValue
 */
export const NullValue = {
  /**
   * Null value.
   *
   * @generated from enum value: NULL_VALUE = 0;
   */
  NULL_VALUE: 0,
} as const;

/**
 * Represents a JSON `null`.
 *
 * `NullValue` is a sentinel, using an enum with only one value to represent
 * the null value for the `Value` type union.
 *
 * A field of type `NullValue` with any value other than `0` is considered
 * invalid. Most ProtoJSON serializers will emit a Value with a `null_value` set
 * as a JSON `null` regardless of the integer value, and so will round trip to
 * a `0` value.
 *
 * @generated from enum google.protobuf.NullValue
 */
export type NullValue = (typeof NullValue)[keyof typeof NullValue];

export const NullValueSchema = S.union([NullValue.NULL_VALUE]);

/**
 * Represents a JSON object.
 *
 * An unordered key-value map, intending to perfectly capture the semantics of a
 * JSON object. This enables parsing any arbitrary JSON payload as a message
 * field in ProtoJSON format.
 *
 * This follows RFC 8259 guidelines for interoperable JSON: notably this type
 * cannot represent large Int64 values or `NaN`/`Infinity` numbers,
 * since the JSON format generally does not support those values in its number
 * type.
 *
 * If you do not intend to parse arbitrary JSON into your message, a custom
 * typed message should be preferred instead of using this type.
 *
 * @generated from message google.protobuf.Struct
 */
export type Struct = {
  /**
   * Unordered map of dynamically typed values.
   *
   * @generated from field: map<string, google.protobuf.Value> fields = 1;
   */
  fields: { [key: string]: Value };
};

/**
 * Represents a JSON value.
 *
 * `Value` represents a dynamically typed value which can be either
 * null, a number, a string, a boolean, a recursive struct value, or a
 * list of values. A producer of value is expected to set one of these
 * variants. Absence of any variant is an invalid state.
 *
 * @generated from message google.protobuf.Value
 */
export type Value = {
  /**
   * The kind of value.
   *
   * @generated from oneof google.protobuf.Value.kind
   */
  kind:
    | { case: "nullValue"; value: NullValue }
    | { case: "numberValue"; value: number }
    | { case: "stringValue"; value: string }
    | { case: "boolValue"; value: boolean }
    | { case: "structValue"; value: Struct }
    | { case: "listValue"; value: ListValue }
    | { case?: undefined; value?: undefined };
};

/**
 * Represents a JSON array.
 *
 * @generated from message google.protobuf.ListValue
 */
export type ListValue = {
  /**
   * Repeated field of dynamically typed values.
   *
   * @generated from field: repeated google.protobuf.Value values = 1;
   */
  values: Value[];
};

export const StructSchema = S.recursive<Struct>("Struct", (self) =>
  S.schema({
    fields: S.protobufField(S.record(S.recursive<Value>("Value", (self2) =>
    S.schema({
      kind: S.union([
        S.schema({ case: "nullValue", value: S.protobufField(NullValueSchema, { number: 1, type: "enum" }) }),
        S.schema({ case: "numberValue", value: S.protobufField($number, { number: 2, type: "double" }) }),
        S.schema({ case: "stringValue", value: S.protobufField(S.string, { number: 3, type: "string" }) }),
        S.schema({ case: "boolValue", value: S.protobufField(S.boolean, { number: 4, type: "bool" }) }),
        S.schema({ case: "structValue", value: S.protobufField(self, { number: 5, type: "message" }) }),
        S.schema({ case: "listValue", value: S.protobufField(S.recursive<ListValue>("ListValue", (_self3) =>
      S.schema({
        values: S.protobufField(S.array(self2), { number: 1, type: "message" }),
      }),
    ), { number: 6, type: "message" }) }),
        S.schema({ case: undefined, value: S.optional(S.schema(undefined)) }),
      ]),
    }),
  )), { number: 1, type: "message", key: "string" }),
  }),
);

export const ValueSchema = S.recursive<Value>("Value", (self) =>
  S.schema({
    kind: S.union([
      S.schema({ case: "nullValue", value: S.protobufField(NullValueSchema, { number: 1, type: "enum" }) }),
      S.schema({ case: "numberValue", value: S.protobufField($number, { number: 2, type: "double" }) }),
      S.schema({ case: "stringValue", value: S.protobufField(S.string, { number: 3, type: "string" }) }),
      S.schema({ case: "boolValue", value: S.protobufField(S.boolean, { number: 4, type: "bool" }) }),
      S.schema({ case: "structValue", value: S.protobufField(S.recursive<Struct>("Struct", (_self2) =>
    S.schema({
      fields: S.protobufField(S.record(self), { number: 1, type: "message", key: "string" }),
    }),
  ), { number: 5, type: "message" }) }),
      S.schema({ case: "listValue", value: S.protobufField(S.recursive<ListValue>("ListValue", (_self2) =>
    S.schema({
      values: S.protobufField(S.array(self), { number: 1, type: "message" }),
    }),
  ), { number: 6, type: "message" }) }),
      S.schema({ case: undefined, value: S.optional(S.schema(undefined)) }),
    ]),
  }),
);

export const ListValueSchema = S.recursive<ListValue>("ListValue", (self) =>
  S.schema({
    values: S.protobufField(S.array(S.recursive<Value>("Value", (self2) =>
    S.schema({
      kind: S.union([
        S.schema({ case: "nullValue", value: S.protobufField(NullValueSchema, { number: 1, type: "enum" }) }),
        S.schema({ case: "numberValue", value: S.protobufField($number, { number: 2, type: "double" }) }),
        S.schema({ case: "stringValue", value: S.protobufField(S.string, { number: 3, type: "string" }) }),
        S.schema({ case: "boolValue", value: S.protobufField(S.boolean, { number: 4, type: "bool" }) }),
        S.schema({ case: "structValue", value: S.protobufField(S.recursive<Struct>("Struct", (_self3) =>
      S.schema({
        fields: S.protobufField(S.record(self2), { number: 1, type: "message", key: "string" }),
      }),
    ), { number: 5, type: "message" }) }),
        S.schema({ case: "listValue", value: S.protobufField(self, { number: 6, type: "message" }) }),
        S.schema({ case: undefined, value: S.optional(S.schema(undefined)) }),
      ]),
    }),
  )), { number: 1, type: "message" }),
  }),
);
