// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Sury from "sury";

let stringSchema = Sury.string;

let error = new Sury.Error({
  code: "invalid_operation",
  path: S.Path.empty,
  reason: "Something went wrong"
});

export {
  stringSchema,
  error,
}
/* stringSchema Not a pure module */
