#!/usr/bin/env bash
#
# Publish packages/benchmarks/.charts to the `benchmarks` branch, which the
# pages under docs/benchmarks/ embed the timings from.
#
# The timings are the one measurement a pull request cannot gate, because they
# move with the runner. They used to be committed back to main on every push,
# which a protected branch declines: a bot cannot open the pull request its own
# rule asks for. So they go to a branch nothing is developed on, and the pages
# reach them by URL - which is what lets the markdown on main stay the same from
# one measurement to the next.
#
# The branch is rewritten to a single commit each run rather than appended to.
# Every push to main republishes all eight files, and a year of them is a year
# of blobs nobody reads.
#
# Usage: scripts/publish-charts.sh   (from the repository root)

set -euo pipefail

charts="$PWD/packages/benchmarks/.charts"
worktree="$PWD/.publish-charts"

if [ ! -d "$charts" ]; then
  echo "no charts to publish: run \`pnpm benchmarks --charts\` first" >&2
  exit 1
fi

# A runner has no identity configured and a contributor's clone does, so this
# supplies one rather than replacing one.
git config user.name >/dev/null || git config user.name "github-actions[bot]"
git config user.email >/dev/null || git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# The orphan is built under a name of its own and pushed to `benchmarks`, so a
# second run in the same clone does not trip over the branch the first one left
# behind.
cleanup() {
  git worktree remove --force "$worktree" 2>/dev/null || true
  git branch -D publish-charts >/dev/null 2>&1 || true
}
trap cleanup EXIT
cleanup

rm -rf "$worktree"
git worktree add --detach "$worktree" >/dev/null
git -C "$worktree" checkout --orphan publish-charts >/dev/null
git -C "$worktree" rm -rq --cached .
find "$worktree" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

cp "$charts"/*.svg "$worktree/"
cat >"$worktree/README.md" <<'EOF'
# Benchmark charts

Generated by `pnpm benchmarks --charts` on every push to `main`, and embedded by
the pages under `docs/benchmarks/` on the default branch. Nothing is developed
here, and this branch is rewritten on every run.
EOF

git -C "$worktree" add -A
git -C "$worktree" commit -qm "chore: republish the benchmark charts"
git -C "$worktree" push --force origin HEAD:benchmarks
