#!/usr/bin/env bash
#
# Publish packages/benchmarks/.charts to the `benchmarks` branch, which the
# pages under docs/benchmarks/ embed the timings from.
#
# The timings are the one measurement a pull request cannot gate, because they
# move with the runner. They used to be committed back to main on every push,
# which a protected branch declines: a bot cannot open the pull request its own
# rule asks for. So they go to a branch nothing is developed on, and the pages
# reach them by URL - which is what lets the markdown on main stay the same from
# one measurement to the next.
#
# The commit is built with plumbing against a temporary index rather than with a
# worktree and a branch of its own. Nothing here touches the checkout, the index
# or the branch namespace of the clone it runs in, so a contributor seeding the
# branch by hand does not have it stand on their work.
#
# The branch is replaced by a single commit each run rather than appended to.
# Every push to main republishes all eight files, and a year of them is a year
# of blobs nobody reads. That is also why the caller has to have rendered every
# topic: a partial `.charts` publishes as the whole branch and breaks the pages
# whose file it leaves out. `pnpm benchmarks --charts` refuses `--only` for that
# reason.
#
# Usage: scripts/publish-charts.sh   (from the repository root)

set -euo pipefail

charts="$PWD/packages/benchmarks/.charts"

if [ ! -d "$charts" ] || [ -z "$(ls -A "$charts"/*.svg 2>/dev/null)" ]; then
  echo "no charts to publish: run \`pnpm benchmarks --charts\` first" >&2
  exit 1
fi

# A runner has no identity configured and a contributor's clone does, so this
# supplies one rather than replacing one.
git config user.name >/dev/null || git config user.name "github-actions[bot]"
git config user.email >/dev/null || git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

GIT_DIR="$(git rev-parse --absolute-git-dir)"
staging="$(mktemp -d)"
GIT_INDEX_FILE="$(mktemp -u)"
export GIT_DIR GIT_INDEX_FILE
trap 'rm -rf "$staging" "$GIT_INDEX_FILE"' EXIT

cp "$charts"/*.svg "$staging/"
cat >"$staging/README.md" <<'EOF'
# Benchmark charts

Generated by `pnpm benchmarks --charts` on every push to `main`, and embedded by
the pages under `docs/benchmarks/` on the default branch. Nothing is developed
here, and this branch is rewritten on every run.
EOF

cd "$staging"
export GIT_WORK_TREE="$staging"
git add -A
tree="$(git write-tree)"
commit="$(git commit-tree "$tree" -m "chore: republish the benchmark charts")"
git push --force origin "$commit:refs/heads/benchmarks"
