// Generated by ReScript, PLEASE EDIT WITH CARE


function classify(arrayable) {
  if (Array.isArray(arrayable)) {
    return {
            TAG: "Array",
            _0: arrayable
          };
  } else {
    return {
            TAG: "Single",
            _0: arrayable
          };
  }
}

var Arrayable = {
  classify: classify
};

var Mutable = {};

var Definition = {};

var Dependency = {};

export {
  Arrayable ,
  Mutable ,
  Definition ,
  Dependency ,
}
/* No side effect */
