// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import * as Vitest from "vitest";

let variantSchema = S.union([
  S.literal("One"),
  S.literal("Two")
]);

Vitest.test("Variant", t => U.assertEqualSchemas(t, variantSchema, S.union([
  S.literal("One"),
  S.literal("Two")
]), undefined));

let variantWithSingleItemSchema = S.literal("Single");

Vitest.test("Variant with single item becomes a literal schema of the item", t => U.assertEqualSchemas(t, variantWithSingleItemSchema, S.literal("Single"), undefined));

let variantWithAliasSchema = S.union([
  S.literal("하나"),
  S.literal("Two")
]);

Vitest.test("Variant with partial @as usage", t => U.assertEqualSchemas(t, variantWithAliasSchema, S.union([
  S.literal("하나"),
  S.literal("Two")
]), undefined));

let variantWithPayloadsSchema = S.union([
  S.literal("Constant"),
  S.schema(s => ({
    TAG: "SinglePayload",
    _0: s.m(S.int)
  })),
  S.schema(s => ({
    TAG: "TuplePayload",
    _0: s.m(S.int),
    _1: s.m(S.string)
  })),
  S.schema(s => ({
    TAG: "RecordPayload",
    foo: s.m(S.float)
  }))
]);

Vitest.test("Variant with payloads", t => U.assertEqualSchemas(t, variantWithPayloadsSchema, S.union([
  S.literal("Constant"),
  S.schema(s => ({
    TAG: "SinglePayload",
    _0: s.m(S.int)
  })),
  S.schema(s => ({
    TAG: "TuplePayload",
    _0: s.m(S.int),
    _1: s.m(S.string)
  })),
  S.schema(s => ({
    TAG: "RecordPayload",
    foo: s.m(S.float)
  }))
]), undefined));

let unboxedVariantSchema = S.union([
  S.literal("Constant"),
  S.schema(s => (s.m(S.int))),
  S.schema(s => (s.m(S.string)))
]);

Vitest.test("Unboxed variant", t => U.assertEqualSchemas(t, unboxedVariantSchema, S.union([
  S.literal("Constant"),
  S.schema(s => (s.m(S.int))),
  S.schema(s => (s.m(S.string)))
]), undefined));

let taggedVariantSchema = S.union([
  S.schema(s => ({
    kind: "circle",
    radius: s.m(S.float)
  })),
  S.schema(s => ({
    kind: "square",
    x: s.m(S.float)
  })),
  S.schema(s => ({
    kind: "triangle",
    x: s.m(S.float),
    y: s.m(S.float)
  }))
]);

Vitest.test("Tagged variant", t => U.assertEqualSchemas(t, taggedVariantSchema, S.union([
  S.schema(s => ({
    kind: "circle",
    radius: s.m(S.float)
  })),
  S.schema(s => ({
    kind: "square",
    x: s.m(S.float)
  })),
  S.schema(s => ({
    kind: "triangle",
    x: s.m(S.float),
    y: s.m(S.float)
  }))
]), undefined));

let strictVariantSchema = S.strict(S.union([
  S.literal("StrictA"),
  S.schema(s => ({
    TAG: "StrictB",
    _0: s.m(S.int)
  }))
]));

let taggedInlinedAliasSchema = S.union([
  S.schema(s => ({
    type: "Foo",
    Foo: s.m(S.string)
  })),
  S.schema(s => ({
    type: "Bar",
    Bar: s.m(S.string)
  }))
]);

Vitest.test("@s.strict on root variant type", t => U.assertEqualSchemas(t, strictVariantSchema, S.strict(S.union([
  S.literal("StrictA"),
  S.schema(s => ({
    TAG: "StrictB",
    _0: s.m(S.int)
  }))
])), undefined));

Vitest.test("Tagged variant with inlined alias", t => U.assertEqualSchemas(t, taggedInlinedAliasSchema, S.union([
  S.schema(s => ({
    type: "Foo",
    Foo: s.m(S.string)
  })),
  S.schema(s => ({
    type: "Bar",
    Bar: s.m(S.string)
  }))
]), undefined));

export {
  variantSchema,
  variantWithSingleItemSchema,
  variantWithAliasSchema,
  variantWithPayloadsSchema,
  unboxedVariantSchema,
  taggedVariantSchema,
  strictVariantSchema,
  taggedInlinedAliasSchema,
}
/* variantSchema Not a pure module */
