// Generated by ReScript, PLEASE EDIT WITH CARE
// Reproduction for Issue #162: PPX support for parametrized types

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import Ava from "ava";

let wrapperSchema = (aSchema) => S.schema(s => ({
  value: s.m(aSchema)
}));

Ava("Parametrized record with single type param — int", t => {
  U.assertEqualSchemas(t, wrapperSchema(S.int), S.schema(s => ({
    value: s.m(S.int)
  })), undefined);
  t.deepEqual(S.parseOrThrow({"value": 42}, wrapperSchema(S.int)), {
    value: 42
  });
});

Ava("Parametrized record with single type param — string", t => {
  U.assertEqualSchemas(t, wrapperSchema(S.string), S.schema(s => ({
    value: s.m(S.string)
  })), undefined);
  t.deepEqual(S.parseOrThrow({"value": "hello"}, wrapperSchema(S.string)), {
    value: "hello"
  });
});

let parentSchema = S.schema(s => ({
  wrapped: s.m(wrapperSchema(S.int))
}));

Ava("Record using parametrized type as field", t => {
  U.assertEqualSchemas(t, parentSchema, S.schema(s => ({
    wrapped: s.m(wrapperSchema(S.int))
  })), undefined);
  t.deepEqual(S.parseOrThrow({"wrapped": {"value": 42}}, parentSchema), {
    wrapped: {
      value: 42
    }
  });
});

let nestedSchema = (aSchema) => S.schema(s => ({
  inner: s.m(wrapperSchema(aSchema))
}));

Ava("Nested parametrized types", t => {
  let schema = nestedSchema(S.string);
  t.deepEqual(S.parseOrThrow({"inner": {"value": "deep"}}, schema), {
    inner: {
      value: "deep"
    }
  });
});

let withOptionSchema = (aSchema) => S.schema(s => ({
  data: s.m(S.option(aSchema))
}));

Ava("Parametrized type with option field", t => {
  let schema = withOptionSchema(S.int);
  t.deepEqual(S.parseOrThrow({"data": 5}, schema), {
    data: 5
  });
  t.deepEqual(S.parseOrThrow({}, schema), {
    data: undefined
  });
});

let withArraySchema = (aSchema) => S.schema(s => ({
  items: s.m(S.array(aSchema))
}));

Ava("Parametrized type with array field", t => {
  let schema = withArraySchema(S.string);
  t.deepEqual(S.parseOrThrow({"items": ["a", "b", "c"]}, schema), {
    items: ["a", "b", "c"]
  });
});

let aliasSchema = (aSchema) => aSchema;

Ava("Parametrized type alias", t => {
  let schema = aliasSchema(S.int);
  t.deepEqual(S.parseOrThrow(42, schema), 42);
});

Ava("Parametrized type round-trip", t => {
  let schema = wrapperSchema(S.int);
  t.deepEqual(
    S.parseOrThrow(
      S.decodeOrThrow({value: 42}, S.reverse(schema)),
      schema
    ),
    {value: 42}
  );
});

export {
  wrapperSchema,
  parentSchema,
  nestedSchema,
  withOptionSchema,
  withArraySchema,
  aliasSchema,
}
/* wrapperSchema Not a pure module */
