// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "../utils/Vitest.res.mjs";
import * as Vitest$1 from "vitest";

let nodeSchema = Sury.recursive("node", nodeSchema => Sury.$res_schema(s => ({
  id: s.m(Sury.string),
  children: s.m(Sury.array(nodeSchema))
})));

Vitest$1.test("Self-recursive record", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow({
    id: "1",
    children: [{
        id: "2",
        children: []
      }]
  }, nodeSchema), {
    id: "1",
    children: [{
        id: "2",
        children: []
      }]
  }, undefined);
  U.assertReverseParsesBack(t, nodeSchema, {
    id: "1",
    children: [{
        id: "2",
        children: []
      }]
  });
});

let treeSchema = Sury.recursive("tree", treeSchema => Sury.union([
  Sury.$res_schema(s => ({
    TAG: "Leaf",
    _0: s.m(Sury.int)
  })),
  Sury.$res_schema(s => ({
    TAG: "Branch",
    _0: s.m(Sury.array(treeSchema))
  }))
]));

Vitest$1.test("Self-recursive variant", t => U.assertReverseParsesBack(t, treeSchema, {
  TAG: "Branch",
  _0: [
    {
      TAG: "Leaf",
      _0: 1
    },
    {
      TAG: "Branch",
      _0: [{
          TAG: "Leaf",
          _0: 2
        }]
    }
  ]
}));

let polyTreeSchema = Sury.recursive("polyTree", polyTreeSchema => Sury.union([
  Sury.$res_schema(s => ({
    NAME: "leaf",
    VAL: s.m(Sury.int)
  })),
  Sury.$res_schema(s => ({
    NAME: "branch",
    VAL: s.m(Sury.array(polyTreeSchema))
  }))
]));

Vitest$1.test("Self-recursive polyvariant", t => U.assertReverseParsesBack(t, polyTreeSchema, {
  NAME: "branch",
  VAL: [
    {
      NAME: "leaf",
      VAL: 1
    },
    {
      NAME: "branch",
      VAL: [{
          NAME: "leaf",
          VAL: 2
        }]
    }
  ]
}));

let chainSchema = Sury.recursive("chain", chainSchema => Sury.$res_schema(s => ({
  next: s.m(Sury.$res_option(chainSchema))
})));

Vitest$1.test("Self-recursive through option", t => U.assertReverseParsesBack(t, chainSchema, {
  next: {
    next: {
      next: undefined
    }
  }
}));

let pairSchema = Sury.recursive("pair", pairSchema => Sury.$res_schema(s => ({
  both: s.m(Sury.$res_option(Sury.$res_schema(s => [
    s.m(pairSchema),
    s.m(pairSchema)
  ])))
})));

Vitest$1.test("Self-recursive through tuple", t => U.assertReverseParsesBack(t, pairSchema, {
  both: [
    {
      both: undefined
    },
    {
      both: undefined
    }
  ]
}));

let notActuallyRecSchema = Sury.int;

Vitest$1.test("A rec type that never references itself stays a plain schema", t => U.assertEqualSchemas(t, notActuallyRecSchema, Sury.int, undefined));

let exprSchema = Sury.recursive("expr", exprSchema => {
  let stmtSchema = Sury.recursive("stmt", stmtSchema => Sury.$res_schema(s => ({
    label: s.m(Sury.string),
    body: s.m(exprSchema)
  })));
  return Sury.union([
    Sury.$res_schema(s => ({
      TAG: "Num",
      _0: s.m(Sury.int)
    })),
    Sury.$res_schema(s => ({
      TAG: "Block",
      _0: s.m(Sury.array(stmtSchema))
    }))
  ]);
});

let stmtSchema = Sury.recursive("stmt", stmtSchema => {
  let exprSchema = Sury.recursive("expr", exprSchema => Sury.union([
    Sury.$res_schema(s => ({
      TAG: "Num",
      _0: s.m(Sury.int)
    })),
    Sury.$res_schema(s => ({
      TAG: "Block",
      _0: s.m(Sury.array(stmtSchema))
    }))
  ]));
  return Sury.$res_schema(s => ({
    label: s.m(Sury.string),
    body: s.m(exprSchema)
  }));
});

Vitest$1.test("Mutually recursive types work from either entry point", t => {
  U.assertReverseParsesBack(t, exprSchema, {
    TAG: "Block",
    _0: [
      {
        label: "a",
        body: {
          TAG: "Num",
          _0: 1
        }
      },
      {
        label: "b",
        body: {
          TAG: "Block",
          _0: []
        }
      }
    ]
  });
  U.assertReverseParsesBack(t, stmtSchema, {
    label: "x",
    body: {
      TAG: "Block",
      _0: [{
          label: "y",
          body: {
            TAG: "Num",
            _0: 2
          }
        }]
    }
  });
});

let aSchema = Sury.recursive("a", aSchema => {
  let bSchema = Sury.recursive("b", bSchema => {
    let cSchema = Sury.recursive("c", cSchema => Sury.$res_schema(s => ({
      a: s.m(Sury.$res_option(aSchema))
    })));
    return Sury.$res_schema(s => ({
      c: s.m(Sury.$res_option(cSchema))
    }));
  });
  return Sury.$res_schema(s => ({
    b: s.m(Sury.$res_option(bSchema))
  }));
});

let bSchema = Sury.recursive("b", bSchema => {
  let cSchema = Sury.recursive("c", cSchema => {
    let aSchema = Sury.recursive("a", aSchema => Sury.$res_schema(s => ({
      b: s.m(Sury.$res_option(bSchema))
    })));
    return Sury.$res_schema(s => ({
      a: s.m(Sury.$res_option(aSchema))
    }));
  });
  return Sury.$res_schema(s => ({
    c: s.m(Sury.$res_option(cSchema))
  }));
});

let cSchema = Sury.recursive("c", cSchema => {
  let aSchema = Sury.recursive("a", aSchema => {
    let bSchema = Sury.recursive("b", bSchema => Sury.$res_schema(s => ({
      c: s.m(Sury.$res_option(cSchema))
    })));
    return Sury.$res_schema(s => ({
      b: s.m(Sury.$res_option(bSchema))
    }));
  });
  return Sury.$res_schema(s => ({
    a: s.m(Sury.$res_option(aSchema))
  }));
});

Vitest$1.test("Three-way mutual cycle works from every entry point", t => {
  U.assertReverseParsesBack(t, aSchema, {
    b: {
      c: {
        a: {
          b: undefined
        }
      }
    }
  });
  U.assertReverseParsesBack(t, bSchema, {
    c: {
      a: {
        b: {
          c: undefined
        }
      }
    }
  });
  U.assertReverseParsesBack(t, cSchema, {
    a: {
      b: {
        c: {
          a: undefined
        }
      }
    }
  });
});

let rootSchema = Sury.recursive("root", rootSchema => {
  let lastSchema = Sury.recursive("last", lastSchema => Sury.$res_schema(s => ({
    back: s.m(Sury.$res_option(rootSchema))
  })));
  let midSchema = Sury.recursive("mid", midSchema => Sury.$res_schema(s => ({
    tail: s.m(Sury.$res_option(lastSchema))
  })));
  return Sury.$res_schema(s => ({
    mid: s.m(Sury.$res_option(midSchema)),
    last: s.m(Sury.$res_option(lastSchema))
  }));
});

let midSchema = Sury.recursive("mid", midSchema => {
  let lastSchema = Sury.recursive("last", lastSchema => {
    let rootSchema = Sury.recursive("root", rootSchema => Sury.$res_schema(s => ({
      mid: s.m(Sury.$res_option(midSchema)),
      last: s.m(Sury.$res_option(lastSchema))
    })));
    return Sury.$res_schema(s => ({
      back: s.m(Sury.$res_option(rootSchema))
    }));
  });
  return Sury.$res_schema(s => ({
    tail: s.m(Sury.$res_option(lastSchema))
  }));
});

let lastSchema = Sury.recursive("last", lastSchema => {
  let rootSchema = Sury.recursive("root", rootSchema => {
    let midSchema = Sury.recursive("mid", midSchema => Sury.$res_schema(s => ({
      tail: s.m(Sury.$res_option(lastSchema))
    })));
    return Sury.$res_schema(s => ({
      mid: s.m(Sury.$res_option(midSchema)),
      last: s.m(Sury.$res_option(lastSchema))
    }));
  });
  return Sury.$res_schema(s => ({
    back: s.m(Sury.$res_option(rootSchema))
  }));
});

Vitest$1.test("A sibling needed by several members is bound once and reused", t => {
  U.assertReverseParsesBack(t, rootSchema, {
    mid: {
      tail: {
        back: undefined
      }
    },
    last: undefined
  });
  U.assertReverseParsesBack(t, midSchema, {
    tail: {
      back: {
        mid: undefined,
        last: undefined
      }
    }
  });
  U.assertReverseParsesBack(t, lastSchema, {
    back: {
      mid: undefined,
      last: {
        back: undefined
      }
    }
  });
});

let leafSchema = Sury.$res_schema(s => ({
  name: s.m(Sury.string)
}));

let holderSchema = Sury.recursive("holder", holderSchema => Sury.$res_schema(s => ({
  leaf: s.m(leafSchema),
  next: s.m(Sury.$res_option(holderSchema))
})));

Vitest$1.test("A rec group member that isn't recursive is left unwrapped and bound first", t => {
  U.assertEqualSchemas(t, leafSchema, Sury.$res_schema(s => ({
    name: s.m(Sury.string)
  })), undefined);
  U.assertReverseParsesBack(t, holderSchema, {
    leaf: {
      name: "a"
    },
    next: {
      leaf: {
        name: "b"
      },
      next: undefined
    }
  });
});

let strictNodeSchema = Sury.recursive("strictNode", strictNodeSchema => Sury.strict(Sury.$res_schema(s => ({
  id: s.m(Sury.string),
  kids: s.m(Sury.array(strictNodeSchema))
}))));

Vitest$1.test("Type-level attributes apply to self-references too", t => U.assertThrowsMessage(t, () => {
  S.parseOrThrow({
    id: "1",
    kids: [{
        id: "2",
        kids: [],
        extra: true
      }]
  }, strictNodeSchema);
}, `Failed at ["kids"]["0"]: Unrecognized key "extra"`, undefined));

let matchesSelfSchema = Sury.recursive("matchesSelf", matchesSelfSchema => Sury.$res_schema(s => ({
  id: s.m(Sury.string),
  children: s.m(Sury.array(matchesSelfSchema))
})));

Vitest$1.test("@s.matches payload can reference the schema being defined", t => U.assertReverseParsesBack(t, matchesSelfSchema, {
  id: "1",
  children: [{
      id: "2",
      children: []
    }]
}));

let cutSchema = Sury.$res_schema(s => ({
  self: s.m(Sury.unknown)
}));

Vitest$1.test("A self-reference fully replaced by @s.matches leaves a plain schema", t => U.assertEqualSchemas(t, cutSchema, Sury.$res_schema(s => ({
  self: s.m(Sury.unknown)
})), undefined));

let aliasedSchema = Sury.recursive("aliased", aliasedSchema => Sury.$res_schema(s => ({
  Id: s.m(Sury.string),
  Kids: s.m(Sury.array(aliasedSchema))
})));

Vitest$1.test("Field aliases survive the recursive wrapper", t => Vitest.Assert.deepEqual(t, S.parseOrThrow({
  Id: "1",
  Kids: [{
      Id: "2",
      Kids: []
    }]
}, aliasedSchema), {
  Id: "1",
  Kids: [{
      Id: "2",
      Kids: []
    }]
}, undefined));

export {
  nodeSchema,
  treeSchema,
  polyTreeSchema,
  chainSchema,
  pairSchema,
  notActuallyRecSchema,
  exprSchema,
  stmtSchema,
  aSchema,
  bSchema,
  cSchema,
  rootSchema,
  midSchema,
  lastSchema,
  leafSchema,
  holderSchema,
  strictNodeSchema,
  matchesSelfSchema,
  cutSchema,
  aliasedSchema,
}
/* nodeSchema Not a pure module */
