// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Sury from "sury";
import * as Vitest from "../utils/Vitest.res.mjs";
import * as Vitest$1 from "vitest";

let addressSchema = Sury.$schema(s => ({
  street: s.m(S.protobufField(Sury.string, 1, undefined, undefined, undefined, undefined))
}));

let userSchema = Sury.$schema(s => ({
  id: s.m(S.protobufField(Sury.int32, 1, undefined, undefined, undefined, undefined)),
  home: s.m(S.protobufField(Sury.$option(addressSchema), 2, undefined, undefined, undefined, undefined))
}));

Vitest$1.test("A PPX record numbered with @s.with is a protobuf message", t => {
  let value = {
    id: 150,
    home: {
      street: "Main"
    }
  };
  let bytes = S.convertOrThrow(value, userSchema, undefined, Sury.protobuf);
  Vitest.Assert.deepEqual(t, S.convertOrThrow(bytes, Sury.protobuf, undefined, userSchema), value, undefined);
});

export {
  addressSchema,
  userSchema,
}
/* addressSchema Not a pure module */
