// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "../utils/Vitest.res.mjs";
import * as Vitest$1 from "vitest";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let strictRecordSchema = Sury.strict(Sury.$res_schema(s => ({
  strictEmail: s.m(Sury.string),
  strictName: s.m(Sury.string)
})));

let stripRecordSchema = Sury.strip(Sury.$res_schema(s => ({
  stripEmail: s.m(Sury.string),
  stripName: s.m(Sury.string)
})));

let deepStrictRecordSchema = Sury.deepStrict(Sury.$res_schema(s => ({
  deepStrictEmail: s.m(Sury.string),
  deepStrictName: s.m(Sury.string)
})));

let deepStripRecordSchema = Sury.deepStrip(Sury.$res_schema(s => ({
  deepStripEmail: s.m(Sury.string),
  deepStripName: s.m(Sury.string)
})));

let noValidationRecordSchema = Sury.noValidation(Sury.$res_schema(s => ({
  noValEmail: s.m(Sury.string),
  noValName: s.m(Sury.string)
})), true);

let metaRecordSchema = Sury.meta(Sury.$res_schema(s => ({
  metaEmail: s.m(Sury.string),
  metaName: s.m(Sury.string)
})), {
  description: "A user record"
});

let combinedRecordSchema = Sury.meta(Sury.strict(Sury.$res_schema(s => ({
  combinedEmail: s.m(Sury.string),
  combinedName: s.m(Sury.string)
}))), {
  description: "Combined attributes"
});

let simpleRecordSchema = Sury.$res_schema(s => ({
  label: s.m(Sury.string),
  value: s.m(Sury.int)
}));

Vitest$1.test("Simple record schema", t => {
  U.assertEqualSchemas(t, simpleRecordSchema, Sury.$res_schema(s => ({
    label: s.m(Sury.string),
    value: s.m(Sury.int)
  })), undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({label:"foo",value:1}, simpleRecordSchema), {
    label: "foo",
    value: 1
  }, undefined);
});

let recordWithAliasSchema = Sury.$res_schema(s => ({
  "aliased-label": s.m(Sury.string),
  value: s.m(Sury.int)
}));

Vitest$1.test("Record schema with alias for field name", t => {
  U.assertEqualSchemas(t, recordWithAliasSchema, Sury.$res_schema(s => ({
    "aliased-label": s.m(Sury.string),
    value: s.m(Sury.int)
  })), undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"aliased-label":"foo",value:1}, recordWithAliasSchema), {
    "aliased-label": "foo",
    value: 1
  }, undefined);
});

let recordWithOptionalSchema = Sury.$res_schema(s => ({
  label: s.m(Sury.$res_option(Sury.string)),
  value: s.m(Sury.$res_option(Sury.int))
}));

Vitest$1.test("Record schema with optional fields", t => {
  U.assertEqualSchemas(t, recordWithOptionalSchema, Sury.$res_schema(s => ({
    label: s.m(Sury.$res_option(Sury.string)),
    value: s.m(Sury.$res_option(Sury.int))
  })), undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"label":"foo",value:1}, recordWithOptionalSchema), {
    label: "foo",
    value: 1
  }, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({}, recordWithOptionalSchema), {
    label: undefined,
    value: undefined
  }, undefined);
});

let emptyRecordSchema = Sury.$res_schema(s => ({}));

Vitest$1.test("Empty record schema", t => Vitest.Assert.deepEqual(t, S.parseOrThrow({}, emptyRecordSchema), {}, undefined));

let recordWithNullableFieldSchema = Sury.$res_schema(s => ({
  subscription: s.m(Sury.$res_option(Sury.$res_nullAsOption(Sury.string)))
}));

Vitest$1.test("Record schema with nullable field", t => {
  U.assertEqualSchemas(t, recordWithNullableFieldSchema, Sury.$res_schema(s => ({
    subscription: s.m(Sury.$res_option(Sury.$res_nullAsOption(Sury.string)))
  })), undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({}, recordWithNullableFieldSchema), {
    subscription: undefined
  }, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"subscription":null}, recordWithNullableFieldSchema), {
    subscription: Primitive_option.some(undefined)
  }, undefined);
});

let recordWithOptionalNullableFieldSchema = Sury.$res_schema(s => ({
  foo: s.m(Sury.$res_nullableAsOption(Sury.string))
}));

Vitest$1.test("Record schema with @s.nullable on optional field", t => {
  U.assertEqualSchemas(t, recordWithOptionalNullableFieldSchema, Sury.$res_schema(s => ({
    foo: s.m(Sury.$res_nullableAsOption(Sury.string))
  })), undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({}, recordWithOptionalNullableFieldSchema), {}, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"foo":null}, recordWithOptionalNullableFieldSchema), {}, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"foo":"bar"}, recordWithOptionalNullableFieldSchema), {
    foo: "bar"
  }, undefined);
});

let recordWithOptionalNullFieldSchema = Sury.$res_schema(s => ({
  foo: s.m(Sury.$res_nullAsOption(Sury.string))
}));

Vitest$1.test("Record schema with @s.null on optional field", t => {
  U.assertEqualSchemas(t, recordWithOptionalNullFieldSchema, Sury.$res_schema(s => ({
    foo: s.m(Sury.$res_nullAsOption(Sury.string))
  })), undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"foo":null}, recordWithOptionalNullFieldSchema), {}, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"foo":"bar"}, recordWithOptionalNullFieldSchema), {
    foo: "bar"
  }, undefined);
  U.assertThrowsMessage(t, () => S.parseOrThrow({}, recordWithOptionalNullFieldSchema), `Failed at ["foo"]: Expected string | null, received undefined`, undefined);
  Vitest.Assert.deepEqual(t, S.decodeOrThrow({}, recordWithOptionalNullFieldSchema, Sury.unknown), {"foo":null}, undefined);
});

Vitest$1.test("@s.strict on root record type", t => U.assertEqualSchemas(t, strictRecordSchema, Sury.strict(Sury.$res_schema(s => ({
  strictEmail: s.m(Sury.string),
  strictName: s.m(Sury.string)
}))), undefined));

Vitest$1.test("@s.strip on root record type", t => U.assertEqualSchemas(t, stripRecordSchema, Sury.strip(Sury.$res_schema(s => ({
  stripEmail: s.m(Sury.string),
  stripName: s.m(Sury.string)
}))), undefined));

Vitest$1.test("@s.deepStrict on root record type", t => U.assertEqualSchemas(t, deepStrictRecordSchema, Sury.deepStrict(Sury.$res_schema(s => ({
  deepStrictEmail: s.m(Sury.string),
  deepStrictName: s.m(Sury.string)
}))), undefined));

Vitest$1.test("@s.deepStrip on root record type", t => U.assertEqualSchemas(t, deepStripRecordSchema, Sury.deepStrip(Sury.$res_schema(s => ({
  deepStripEmail: s.m(Sury.string),
  deepStripName: s.m(Sury.string)
}))), undefined));

Vitest$1.test("@s.noValidation on root record type", t => U.assertEqualSchemas(t, noValidationRecordSchema, Sury.noValidation(Sury.$res_schema(s => ({
  noValEmail: s.m(Sury.string),
  noValName: s.m(Sury.string)
})), true), undefined));

Vitest$1.test("@s.meta on root record type", t => U.assertEqualSchemas(t, metaRecordSchema, Sury.meta(Sury.$res_schema(s => ({
  metaEmail: s.m(Sury.string),
  metaName: s.m(Sury.string)
})), {
  description: "A user record"
}), undefined));

Vitest$1.test("Multiple @s.* attributes on root record type", t => U.assertEqualSchemas(t, combinedRecordSchema, Sury.meta(Sury.strict(Sury.$res_schema(s => ({
  combinedEmail: s.m(Sury.string),
  combinedName: s.m(Sury.string)
}))), {
  description: "Combined attributes"
}), undefined));

let schema = Sury.$res_schema(s => ({
  id: s.m(Sury.string),
  summary: s.m(Sury.$res_option(Sury.string))
}));

let Meta = {
  schema: schema
};

let recordWithSpreadSchema = Sury.$res_schema(s => Object.assign({
  messages: s.m(Sury.array(Sury.string))
}, schema.properties));

Vitest$1.test("Record schema with type spread", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc",summary:"hello",messages:["a","b"]}, recordWithSpreadSchema), {
    id: "abc",
    summary: "hello",
    messages: [
      "a",
      "b"
    ]
  }, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc",messages:[]}, recordWithSpreadSchema), {
    id: "abc",
    summary: undefined,
    messages: []
  }, undefined);
  U.assertReverseReversesBack(t, recordWithSpreadSchema);
});

let schema$1 = Sury.$res_schema(s => ({
  score: s.m(Sury.float)
}));

let Extra = {
  schema: schema$1
};

let recordWithMultipleSpreadsSchema = Sury.$res_schema(s => Object.assign({
  active: s.m(Sury.bool)
}, schema.properties, schema$1.properties));

Vitest$1.test("Record schema with multiple type spreads", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc",summary:"hello",score:9.5,active:true}, recordWithMultipleSpreadsSchema), {
    id: "abc",
    summary: "hello",
    score: 9.5,
    active: true
  }, undefined);
  U.assertReverseReversesBack(t, recordWithMultipleSpreadsSchema);
});

let recordWithOnlySpreadSchema = Sury.$res_schema(_s => Object.assign({}, schema.properties));

Vitest$1.test("Record schema with only a spread (no own fields)", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc",summary:"hi"}, recordWithOnlySpreadSchema), {
    id: "abc",
    summary: "hi"
  }, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc"}, recordWithOnlySpreadSchema), {
    id: "abc",
    summary: undefined
  }, undefined);
  U.assertReverseReversesBack(t, recordWithOnlySpreadSchema);
});

let recordWithMultipleSpreadsNoFieldsSchema = Sury.$res_schema(_s => Object.assign({}, schema.properties, schema$1.properties));

Vitest$1.test("Record schema with multiple spreads and no own fields", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc",summary:"hi",score:5.0}, recordWithMultipleSpreadsNoFieldsSchema), {
    id: "abc",
    summary: "hi",
    score: 5.0
  }, undefined);
  U.assertReverseReversesBack(t, recordWithMultipleSpreadsNoFieldsSchema);
});

let recordWithSpreadAndAliasedFieldSchema = Sury.$res_schema(s => Object.assign({
  ms: s.m(Sury.array(Sury.string))
}, schema.properties));

Vitest$1.test("Record schema with spread and @as-aliased own field", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc",summary:"hi",ms:["a"]}, recordWithSpreadAndAliasedFieldSchema), {
    id: "abc",
    summary: "hi",
    ms: ["a"]
  }, undefined);
  U.assertReverseReversesBack(t, recordWithSpreadAndAliasedFieldSchema);
});

let recordWithSpreadAndOptionalFieldSchema = Sury.$res_schema(s => Object.assign({
  extra: s.m(Sury.$res_option(Sury.int))
}, schema.properties));

Vitest$1.test("Record schema with spread and optional own field", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc",summary:"hi",extra:5}, recordWithSpreadAndOptionalFieldSchema), {
    id: "abc",
    summary: "hi",
    extra: 5
  }, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id:"abc"}, recordWithSpreadAndOptionalFieldSchema), {
    id: "abc",
    summary: undefined,
    extra: undefined
  }, undefined);
  U.assertReverseReversesBack(t, recordWithSpreadAndOptionalFieldSchema);
});

export {
  strictRecordSchema,
  stripRecordSchema,
  deepStrictRecordSchema,
  deepStripRecordSchema,
  noValidationRecordSchema,
  metaRecordSchema,
  combinedRecordSchema,
  simpleRecordSchema,
  recordWithAliasSchema,
  recordWithOptionalSchema,
  emptyRecordSchema,
  recordWithNullableFieldSchema,
  recordWithOptionalNullableFieldSchema,
  recordWithOptionalNullFieldSchema,
  Meta,
  recordWithSpreadSchema,
  Extra,
  recordWithMultipleSpreadsSchema,
  recordWithOnlySpreadSchema,
  recordWithMultipleSpreadsNoFieldsSchema,
  recordWithSpreadAndAliasedFieldSchema,
  recordWithSpreadAndOptionalFieldSchema,
}
/* strictRecordSchema Not a pure module */
