// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Vitest from "../utils/Vitest.res.mjs";
import * as Vitest$1 from "vitest";

function wrapperSchema(_aSchema) {
  return S.schema(s => ({
    value: s.m(_aSchema)
  }));
}

Vitest$1.test("Parametrized record with single type param — int", t => {
  let schema = wrapperSchema(S.int);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"value": 42}, schema), {
    value: 42
  }, undefined);
});

Vitest$1.test("Parametrized record with single type param — string", t => {
  let schema = wrapperSchema(S.string);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"value": "hello"}, schema), {
    value: "hello"
  }, undefined);
});

let parentSchema = S.schema(s => ({
  wrapped: s.m(wrapperSchema(S.int))
}));

Vitest$1.test("Record using parametrized type as field", t => Vitest.Assert.deepEqual(t, S.parseOrThrow({"wrapped": {"value": 42}}, parentSchema), {
  wrapped: {
    value: 42
  }
}, undefined));

function nestedSchema(_aSchema) {
  return S.schema(s => ({
    inner: s.m(wrapperSchema(_aSchema))
  }));
}

Vitest$1.test("Nested parametrized types", t => {
  let schema = nestedSchema(S.string);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"inner": {"value": "deep"}}, schema), {
    inner: {
      value: "deep"
    }
  }, undefined);
});

function withOptionSchema(_aSchema) {
  return S.schema(s => ({
    data: s.m(S.option(_aSchema))
  }));
}

Vitest$1.test("Parametrized type with option field", t => {
  let schema = withOptionSchema(S.int);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"data": 5}, schema), {
    data: 5
  }, undefined);
});

function withArraySchema(_aSchema) {
  return S.schema(s => ({
    items: s.m(S.array(_aSchema))
  }));
}

Vitest$1.test("Parametrized type with array field", t => {
  let schema = withArraySchema(S.string);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"items": ["a", "b", "c"]}, schema), {
    items: [
      "a",
      "b",
      "c"
    ]
  }, undefined);
});

function result2Schema(aSchema, bSchema) {
  return S.union([
    S.schema(s => ({
      TAG: "R2A",
      _0: s.m(aSchema)
    })),
    S.schema(s => ({
      TAG: "R2B",
      _0: s.m(bSchema)
    }))
  ]);
}

let holderSchema = S.schema(s => ({
  res: s.m(result2Schema(S.int, S.string))
}));

Vitest$1.test("Record field with @s.matches override for a 2-param type", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"res": {"TAG": "R2A", "_0": 1}}, holderSchema), {
    res: {
      TAG: "R2A",
      _0: 1
    }
  }, undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({"res": {"TAG": "R2B", "_0": "boom"}}, holderSchema), {
    res: {
      TAG: "R2B",
      _0: "boom"
    }
  }, undefined);
});

function idSchema(_aSchema) {
  return S.string;
}

Vitest$1.test("Parametrized type alias whose param is unused (phantom)", t => {
  let schema = S.string;
  Vitest.Assert.deepEqual(t, S.parseOrThrow("hello", schema), "hello", undefined);
});

export {
  wrapperSchema,
  parentSchema,
  nestedSchema,
  withOptionSchema,
  withArraySchema,
  result2Schema,
  holderSchema,
  idSchema,
}
/*  Not a pure module */
