// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "../utils/Vitest.res.mjs";
import * as Vitest$1 from "vitest";

let payloadSchema = Sury.$schema(s => ({
  a: s.m(Sury.$option(Sury.string))
}));

let schema = Sury.$schema(s => ({
  payload: s.m(payloadSchema)
}));

let A = {
  payloadSchema: payloadSchema,
  schema: schema
};

let payloadSchema$1 = Sury.$schema(s => ({
  b: s.m(Sury.$option(Sury.int))
}));

let schema$1 = Sury.$schema(s => ({
  payload: s.m(payloadSchema$1)
}));

let B = {
  payloadSchema: payloadSchema$1,
  schema: schema$1
};

Vitest$1.test("Union serializing of objects with optional fields", t => {
  let schema$2 = Sury.union([
    Sury.shape(schema, m => ({
      TAG: "A",
      _0: m
    })),
    Sury.shape(schema$1, m => ({
      TAG: "B",
      _0: m
    }))
  ]);
  U.assertCompiledCode(t, schema$2, "Encode", `i=>{for(;;){if(typeof i==="object"&&i&&!Array.isArray(i)&&i["TAG"]==="A"){let v0=i["_0"];typeof v0==="object"&&v0&&!Array.isArray(v0)||e[2](v0);let v1=v0["payload"];typeof v1==="object"&&v1&&!Array.isArray(v1)||e[1](v1);let v2=v1["a"];(typeof v2==="string"||v2===void 0)||e[0](v2);i={"payload":{"a":v2,},};break}if(typeof i==="object"&&i&&!Array.isArray(i)&&i["TAG"]==="B"){let v3=i["_0"];typeof v3==="object"&&v3&&!Array.isArray(v3)||e[5](v3);let v4=v3["payload"];typeof v4==="object"&&v4&&!Array.isArray(v4)||e[4](v4);let v5=v4["b"];(typeof v5==="number"&&!Number.isNaN(v5)&&v5<=2147483647&&v5>=-2147483648&&v5%1===0||v5===void 0)||e[3](v5);i={"payload":{"b":v5,},};break}e[6](i)}return i}`, undefined);
  Vitest.Assert.deepEqual(t, S.decodeOrThrow({
    TAG: "B",
    _0: {
      payload: {
        b: 42
      }
    }
  }, schema$2, Sury.unknown), {"payload":{"b":42}}, undefined);
  Vitest.Assert.deepEqual(t, S.decodeOrThrow({
    TAG: "A",
    _0: {
      payload: {
        a: "foo"
      }
    }
  }, schema$2, Sury.unknown), {"payload":{"a":"foo"}}, undefined);
});

let CknittelBugReport = {
  A: A,
  B: B
};

let aSchema = Sury.$schema(s => ({
  x: s.m(Sury.int)
}));

let bSchema = Sury.$schema(s => ({
  y: s.m(Sury.string)
}));

let testSchema = Sury.union([
  Sury.object(s => {
    s.tag("type", "a");
    return {
      TAG: "A",
      _0: s.flatten(aSchema)
    };
  }),
  Sury.object(s => {
    s.tag("type", "b");
    return {
      TAG: "B",
      _0: s.flatten(bSchema)
    };
  })
]);

let schema$2 = Sury.$schema(s => ({
  test: s.m(Sury.$option(testSchema))
}));

Vitest$1.test("Successfully parses nested optional union", t => {
  U.assertCompiledCode(t, schema$2, "Parse", `i=>{typeof i==="object"&&i&&!Array.isArray(i)||e[3](i);let v0=i["test"];for(;;){if(typeof v0==="object"&&v0&&!Array.isArray(v0)&&v0["type"]==="a"){let v1=v0["x"];typeof v1==="number"&&v1<=2147483647&&v1>=-2147483648&&v1%1===0||e[0](v1);v0={"TAG":"A","_0":{"x":v1,},};break}if(typeof v0==="object"&&v0&&!Array.isArray(v0)&&v0["type"]==="b"){let v2=v0["y"];typeof v2==="string"||e[1](v2);v0={"TAG":"B","_0":{"y":v2,},};break}if(v0===void 0)break;e[2](v0)}return {"test":v0,}}`, undefined);
  Vitest.Assert.deepEqual(t, S.decodeOrThrow("{}", Sury.jsonString, schema$2), {
    test: undefined
  }, undefined);
});

Vitest$1.test("Nested literal field with catch", t => {
  let schema = Sury.union([
    Sury.object(s => {
      s.nested("statusCode").f("kind", Sury.literal("ok"));
      return {
        TAG: "Ok",
        _0: undefined
      };
    }),
    Sury.object(s => {
      s.nested("statusCode").f("kind", Sury.literal("serviceError"));
      return {
        TAG: "Error",
        _0: {
          serviceCode: s.nested("statusCode").f("serviceCode", Sury.string),
          text: s.nested("statusCode").f("text", Sury.string)
        }
      };
    })
  ]);
  U.assertCompiledCode(t, schema, "Parse", `i=>{for(;;){let r;if(typeof i==="object"&&i&&!Array.isArray(i)){try{let v0=i["statusCode"];typeof v0==="object"&&v0&&!Array.isArray(v0)&&v0["kind"]==="ok"||e[0](v0);i={"TAG":"Ok","_0":void 0,};break}catch(x){(r||(r=[])).push(e[4](x))}try{let v1=i["statusCode"];typeof v1==="object"&&v1&&!Array.isArray(v1)&&v1["kind"]==="serviceError"||e[3](v1);let v2=v1["serviceCode"],v3=v1["text"];typeof v2==="string"||e[1](v2);typeof v3==="string"||e[2](v3);i={"TAG":"Error","_0":{"serviceCode":v2,"text":v3,},};break}catch(x){(r||(r=[])).push(e[4](x))}}e[5](i,...(r||[]))}return i}`, undefined);
  Vitest.Assert.deepEqual(t, S.decodeOrThrow(`{"statusCode": {"kind": "ok"}}`, Sury.jsonString, schema), {
    TAG: "Ok",
    _0: undefined
  }, undefined);
});

let CknittelBugReport2 = {
  aSchema: aSchema,
  bSchema: bSchema,
  testSchema: testSchema,
  schema: schema$2
};

export {
  CknittelBugReport,
  CknittelBugReport2,
}
/* payloadSchema Not a pure module */
